//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.HISFC.WinForms.Resources.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FS.HISFC.WinForms.Resources.LanguageResource.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Charge 的本地化字符串。
        /// </summary>
        public static string S收费 {
            get {
                return ResourceManager.GetString("S收费", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal Combination 的本地化字符串。
        /// </summary>
        public static string 个人组套 {
            get {
                return ResourceManager.GetString("个人组套", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Patent Drug 的本地化字符串。
        /// </summary>
        public static string 中成药 {
            get {
                return ResourceManager.GetString("中成药", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Herbal Medicine 的本地化字符串。
        /// </summary>
        public static string 中草药 {
            get {
                return ResourceManager.GetString("中草药", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consultation 的本地化字符串。
        /// </summary>
        public static string 会诊 {
            get {
                return ResourceManager.GetString("会诊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administration 的本地化字符串。
        /// </summary>
        public static string 使用方法 {
            get {
                return ResourceManager.GetString("使用方法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string 保存 {
            get {
                return ResourceManager.GetString("保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Succesed 的本地化字符串。
        /// </summary>
        public static string 保存成功 {
            get {
                return ResourceManager.GetString("保存成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string 修改 {
            get {
                return ResourceManager.GetString("修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify User 的本地化字符串。
        /// </summary>
        public static string 修改用户 {
            get {
                return ResourceManager.GetString("修改用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drug Classification 的本地化字符串。
        /// </summary>
        public static string 全部药品信息 {
            get {
                return ResourceManager.GetString("全部药品信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hospital Combination 的本地化字符串。
        /// </summary>
        public static string 全院组套 {
            get {
                return ResourceManager.GetString("全院组套", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string 其它 {
            get {
                return ResourceManager.GetString("其它", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Constants 的本地化字符串。
        /// </summary>
        public static string 删除常数 {
            get {
                return ResourceManager.GetString("删除常数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Succesed 的本地化字符串。
        /// </summary>
        public static string 删除成功 {
            get {
                return ResourceManager.GetString("删除成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Reports 的本地化字符串。
        /// </summary>
        public static string 删除报表 {
            get {
                return ResourceManager.GetString("删除报表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Menu 的本地化字符串。
        /// </summary>
        public static string 删除菜单 {
            get {
                return ResourceManager.GetString("删除菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Role 的本地化字符串。
        /// </summary>
        public static string 删除角色 {
            get {
                return ResourceManager.GetString("删除角色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string 刷新 {
            get {
                return ResourceManager.GetString("刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommendation 的本地化字符串。
        /// </summary>
        public static string 医嘱 {
            get {
                return ResourceManager.GetString("医嘱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green:New Blue:Exec Red:Cancel 的本地化字符串。
        /// </summary>
        public static string 医嘱颜色信息提示 {
            get {
                return ResourceManager.GetString("医嘱颜色信息提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History Recommendation 的本地化字符串。
        /// </summary>
        public static string 历史医嘱 {
            get {
                return ResourceManager.GetString("历史医嘱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material 的本地化字符串。
        /// </summary>
        public static string 原料 {
            get {
                return ResourceManager.GetString("原料", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoice NO 的本地化字符串。
        /// </summary>
        public static string 发票号 {
            get {
                return ResourceManager.GetString("发票号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string 名称 {
            get {
                return ResourceManager.GetString("名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string 增加 {
            get {
                return ResourceManager.GetString("增加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Constants 的本地化字符串。
        /// </summary>
        public static string 增加常数 {
            get {
                return ResourceManager.GetString("增加常数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Reports 的本地化字符串。
        /// </summary>
        public static string 增加报表 {
            get {
                return ResourceManager.GetString("增加报表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add User 的本地化字符串。
        /// </summary>
        public static string 增加用户 {
            get {
                return ResourceManager.GetString("增加用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Menu 的本地化字符串。
        /// </summary>
        public static string 增加菜单 {
            get {
                return ResourceManager.GetString("增加菜单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Role 的本地化字符串。
        /// </summary>
        public static string 增加角色 {
            get {
                return ResourceManager.GetString("增加角色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecipeNO 的本地化字符串。
        /// </summary>
        public static string 处方号 {
            get {
                return ResourceManager.GetString("处方号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string 复制 {
            get {
                return ResourceManager.GetString("复制", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string 导入 {
            get {
                return ResourceManager.GetString("导入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string 导出 {
            get {
                return ResourceManager.GetString("导出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Succesed 的本地化字符串。
        /// </summary>
        public static string 导出成功 {
            get {
                return ResourceManager.GetString("导出成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant Name 的本地化字符串。
        /// </summary>
        public static string 常数名称 {
            get {
                return ResourceManager.GetString("常数名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail Maintenance 的本地化字符串。
        /// </summary>
        public static string 弹出维护 {
            get {
                return ResourceManager.GetString("弹出维护", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Print 的本地化字符串。
        /// </summary>
        public static string 手动打印 {
            get {
                return ResourceManager.GetString("手动打印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Print 的本地化字符串。
        /// </summary>
        public static string 手工打印 {
            get {
                return ResourceManager.GetString("手工打印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string 手术 {
            get {
                return ResourceManager.GetString("手术", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string 打印 {
            get {
                return ResourceManager.GetString("打印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tend Level 的本地化字符串。
        /// </summary>
        public static string 护理级别 {
            get {
                return ResourceManager.GetString("护理级别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Name 的本地化字符串。
        /// </summary>
        public static string 报表名称 {
            get {
                return ResourceManager.GetString("报表名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Code 的本地化字符串。
        /// </summary>
        public static string 拼音码 {
            get {
                return ResourceManager.GetString("拼音码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Describe Recommendation 的本地化字符串。
        /// </summary>
        public static string 描述医嘱 {
            get {
                return ResourceManager.GetString("描述医嘱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        public static string 操作员 {
            get {
                return ResourceManager.GetString("操作员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find User 的本地化字符串。
        /// </summary>
        public static string 查找用户 {
            get {
                return ResourceManager.GetString("查找用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string 查询 {
            get {
                return ResourceManager.GetString("查询", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exam 的本地化字符串。
        /// </summary>
        public static string 检查 {
            get {
                return ResourceManager.GetString("检查", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checkup 的本地化字符串。
        /// </summary>
        public static string 检验 {
            get {
                return ResourceManager.GetString("检验", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dose 的本地化字符串。
        /// </summary>
        public static string 每次剂量 {
            get {
                return ResourceManager.GetString("每次剂量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Treatment 的本地化字符串。
        /// </summary>
        public static string 治疗 {
            get {
                return ResourceManager.GetString("治疗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Authorization 的本地化字符串。
        /// </summary>
        public static string 用户授权 {
            get {
                return ResourceManager.GetString("用户授权", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case No 的本地化字符串。
        /// </summary>
        public static string 病例卡号 {
            get {
                return ResourceManager.GetString("病例卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outpatient Record 的本地化字符串。
        /// </summary>
        public static string 病历 {
            get {
                return ResourceManager.GetString("病历", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disease Condition 的本地化字符串。
        /// </summary>
        public static string 病情 {
            get {
                return ResourceManager.GetString("病情", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple Maintenance 的本地化字符串。
        /// </summary>
        public static string 直接维护 {
            get {
                return ResourceManager.GetString("直接维护", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple Maintenance Setting 的本地化字符串。
        /// </summary>
        public static string 直接维护列设置 {
            get {
                return ResourceManager.GetString("直接维护列设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        public static string 科室 {
            get {
                return ResourceManager.GetString("科室", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department Combination 的本地化字符串。
        /// </summary>
        public static string 科室组套 {
            get {
                return ResourceManager.GetString("科室组套", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTime 的本地化字符串。
        /// </summary>
        public static string 系统时间 {
            get {
                return ResourceManager.GetString("系统时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combination 的本地化字符串。
        /// </summary>
        public static string 组套 {
            get {
                return ResourceManager.GetString("组套", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string 编码 {
            get {
                return ResourceManager.GetString("编码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diet 的本地化字符串。
        /// </summary>
        public static string 膳食 {
            get {
                return ResourceManager.GetString("膳食", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Print 的本地化字符串。
        /// </summary>
        public static string 自动打印 {
            get {
                return ResourceManager.GetString("自动打印", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Code 的本地化字符串。
        /// </summary>
        public static string 自定义码 {
            get {
                return ResourceManager.GetString("自定义码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Drug 的本地化字符串。
        /// </summary>
        public static string 药品列表 {
            get {
                return ResourceManager.GetString("药品列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string 药品名称 {
            get {
                return ResourceManager.GetString("药品名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nature Of The Drug 的本地化字符串。
        /// </summary>
        public static string 药品性质 {
            get {
                return ResourceManager.GetString("药品性质", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Pharmacological Effect 的本地化字符串。
        /// </summary>
        public static string 药理作用查询 {
            get {
                return ResourceManager.GetString("药理作用查询", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu Name 的本地化字符串。
        /// </summary>
        public static string 菜单名称 {
            get {
                return ResourceManager.GetString("菜单名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu Authorization 的本地化字符串。
        /// </summary>
        public static string 菜单授权 {
            get {
                return ResourceManager.GetString("菜单授权", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 West Medicine 的本地化字符串。
        /// </summary>
        public static string 西药 {
            get {
                return ResourceManager.GetString("西药", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specs 的本地化字符串。
        /// </summary>
        public static string 规格 {
            get {
                return ResourceManager.GetString("规格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure 的本地化字符串。
        /// </summary>
        public static string 计量 {
            get {
                return ResourceManager.GetString("计量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set 的本地化字符串。
        /// </summary>
        public static string 设置 {
            get {
                return ResourceManager.GetString("设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnosis 的本地化字符串。
        /// </summary>
        public static string 诊断 {
            get {
                return ResourceManager.GetString("诊断", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource Name 的本地化字符串。
        /// </summary>
        public static string 资源名称 {
            get {
                return ResourceManager.GetString("资源名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Bed 的本地化字符串。
        /// </summary>
        public static string 转床 {
            get {
                return ResourceManager.GetString("转床", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer Department 的本地化字符串。
        /// </summary>
        public static string 转科 {
            get {
                return ResourceManager.GetString("转科", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Recommendation 的本地化字符串。
        /// </summary>
        public static string 选择医嘱 {
            get {
                return ResourceManager.GetString("选择医嘱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out-Patient Medical WorkStation 的本地化字符串。
        /// </summary>
        public static string 门诊医生 {
            get {
                return ResourceManager.GetString("门诊医生", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out-Patient Medical WorkStation 的本地化字符串。
        /// </summary>
        public static string 门诊医生站 {
            get {
                return ResourceManager.GetString("门诊医生站", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outpatient Record 的本地化字符串。
        /// </summary>
        public static string 门诊病历 {
            get {
                return ResourceManager.GetString("门诊病历", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval 的本地化字符串。
        /// </summary>
        public static string 间隔时间 {
            get {
                return ResourceManager.GetString("间隔时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-Drug 的本地化字符串。
        /// </summary>
        public static string 非药品 {
            get {
                return ResourceManager.GetString("非药品", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query Non-Drug 的本地化字符串。
        /// </summary>
        public static string 非药品列表 {
            get {
                return ResourceManager.GetString("非药品列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial No. 的本地化字符串。
        /// </summary>
        public static string 顺序号 {
            get {
                return ResourceManager.GetString("顺序号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave Hospital 的本地化字符串。
        /// </summary>
        public static string 预约出院 {
            get {
                return ResourceManager.GetString("预约出院", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string 预览 {
            get {
                return ResourceManager.GetString("预览", resourceCulture);
            }
        }
    }
}
