namespace Neusoft.UFC.DCP.DiseaseReport
{
    using FarPoint.Win;
    using FarPoint.Win.Spread;
    using FarPoint.Win.Spread.CellType;
    using FarPoint.Win.Spread.Model;
    using Neusoft.FrameWork.WinForms.Controls;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class ucPrint : ucBaseControl
    {
        public RadioButton cbxHomeAearFive;
        public RadioButton cbxHomeAearFour;
        public RadioButton cbxHomeAearOne;
        public RadioButton cbxHomeAearSix;
        public RadioButton cbxHomeAearThree;
        public RadioButton cbxHomeAearTwo;
        private IContainer components = null;
        private Label label1;
        private Label label13;
        private Label label35;
        private Label label37;
        private Label label39;
        private Label label41;
        private Label label42;
        private Label label43;
        private Label label46;
        private Label label47;
        private Label label48;
        private Label label49;
        private Label label59;
        private Label label60;
        private Label label61;
        private Label label63;
        private Label label64;
        private Label label65;
        private Label label66;
        private Label label68;
        private Label label69;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label labelClinic;
        private Label labless;
        public NeuLabel lbAge;
        public NeuLabel lbBirthday;
        public NeuLabel lbCase;
        public NeuLabel lbCaseClaseTwo;
        public NeuLabel lbCaseClassOne;
        public NeuLabel lbClinicNO;
        public NeuLabel lbDeadDate;
        private Label lbDeadDateLable;
        public NeuLabel lbDiaDate;
        public NeuLabel lbDoctorDept;
        public NeuLabel lbID;
        public NeuLabel lbInfectionClass;
        public NeuLabel lbInfectionDate;
        public NeuLabel lbPatientID;
        public NeuLabel lbPatientName;
        public NeuLabel lbPatientParents;
        public NeuLabel lbProfession;
        public NeuLabel lbReportDoctor;
        public NeuLabel lbReportTime;
        public NeuLabel lbSex;
        public NeuLabel lbSpecificlAddress;
        public NeuLabel lbState;
        public NeuLabel lbTelephone;
        public NeuLabel lbWorkPlace;
        private NeuPanel neuPanel1;
        private NeuPanel neuPanel2;
        private NeuPanel neuPanel3;
        private NeuPanel neuPanel4;
        private NeuPanel neuPanel5;
        private NeuPanel neuPanel6;
        private NeuPanel neuPanel7;
        private NeuSpread neuSpread1;
        public SheetView neuSpread1_Sheet1;
        private NeuPanel panelRbuttom;
        private NeuPanel panelRtop1;
        private NeuPanel panelRtop2;
        private NeuPanel panelRtop3;
        public RadioButton rdbDay;
        public RadioButton rdbInfectionOtherNo;
        public RadioButton rdbInfectOtherYes;
        public RadioButton rdbMonth;
        public RadioButton rdbYear;

        public ucPrint()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            TipAppearance appearance = new TipAppearance();
            TextCellType type = new TextCellType();
            this.panelRbuttom = new NeuPanel();
            this.neuSpread1 = new NeuSpread();
            this.neuSpread1_Sheet1 = new SheetView();
            this.lbReportTime = new NeuLabel();
            this.neuPanel6 = new NeuPanel();
            this.neuPanel5 = new NeuPanel();
            this.lbDoctorDept = new NeuLabel();
            this.lbReportDoctor = new NeuLabel();
            this.lbCase = new NeuLabel();
            this.label35 = new Label();
            this.label9 = new Label();
            this.label37 = new Label();
            this.label39 = new Label();
            this.label41 = new Label();
            this.panelRtop3 = new NeuPanel();
            this.lbDeadDate = new NeuLabel();
            this.lbDiaDate = new NeuLabel();
            this.lbInfectionDate = new NeuLabel();
            this.lbCaseClaseTwo = new NeuLabel();
            this.lbCaseClassOne = new NeuLabel();
            this.lbInfectionClass = new NeuLabel();
            this.lbDeadDateLable = new Label();
            this.rdbInfectionOtherNo = new RadioButton();
            this.rdbInfectOtherYes = new RadioButton();
            this.label42 = new Label();
            this.label46 = new Label();
            this.label47 = new Label();
            this.label43 = new Label();
            this.label48 = new Label();
            this.panelRtop2 = new NeuPanel();
            this.neuPanel4 = new NeuPanel();
            this.lbWorkPlace = new NeuLabel();
            this.lbProfession = new NeuLabel();
            this.lbTelephone = new NeuLabel();
            this.lbSpecificlAddress = new NeuLabel();
            this.lbAge = new NeuLabel();
            this.lbBirthday = new NeuLabel();
            this.lbPatientID = new NeuLabel();
            this.lbSex = new NeuLabel();
            this.lbPatientParents = new NeuLabel();
            this.lbPatientName = new NeuLabel();
            this.neuPanel1 = new NeuPanel();
            this.cbxHomeAearTwo = new RadioButton();
            this.cbxHomeAearOne = new RadioButton();
            this.cbxHomeAearThree = new RadioButton();
            this.cbxHomeAearFour = new RadioButton();
            this.cbxHomeAearFive = new RadioButton();
            this.cbxHomeAearSix = new RadioButton();
            this.label1 = new Label();
            this.label49 = new Label();
            this.label13 = new Label();
            this.label8 = new Label();
            this.label7 = new Label();
            this.rdbDay = new RadioButton();
            this.rdbMonth = new RadioButton();
            this.rdbYear = new RadioButton();
            this.label59 = new Label();
            this.label60 = new Label();
            this.labless = new Label();
            this.label64 = new Label();
            this.label61 = new Label();
            this.label63 = new Label();
            this.label65 = new Label();
            this.panelRtop1 = new NeuPanel();
            this.lbClinicNO = new NeuLabel();
            this.lbID = new NeuLabel();
            this.lbState = new NeuLabel();
            this.neuPanel3 = new NeuPanel();
            this.labelClinic = new Label();
            this.label68 = new Label();
            this.label66 = new Label();
            this.label69 = new Label();
            this.neuPanel2 = new NeuPanel();
            this.neuPanel7 = new NeuPanel();
            this.panelRbuttom.SuspendLayout();
            ((ISupportInitialize) this.neuSpread1).BeginInit();
            ((ISupportInitialize) this.neuSpread1_Sheet1).BeginInit();
            this.panelRtop3.SuspendLayout();
            this.panelRtop2.SuspendLayout();
            this.neuPanel1.SuspendLayout();
            this.panelRtop1.SuspendLayout();
            base.SuspendLayout();
            this.panelRbuttom.BackColor = Color.White;
            this.panelRbuttom.Controls.Add(this.neuSpread1);
            this.panelRbuttom.Controls.Add(this.lbReportTime);
            this.panelRbuttom.Controls.Add(this.neuPanel6);
            this.panelRbuttom.Controls.Add(this.neuPanel5);
            this.panelRbuttom.Controls.Add(this.lbDoctorDept);
            this.panelRbuttom.Controls.Add(this.lbReportDoctor);
            this.panelRbuttom.Controls.Add(this.lbCase);
            this.panelRbuttom.Controls.Add(this.label35);
            this.panelRbuttom.Controls.Add(this.label9);
            this.panelRbuttom.Controls.Add(this.label37);
            this.panelRbuttom.Controls.Add(this.label39);
            this.panelRbuttom.Controls.Add(this.label41);
            this.panelRbuttom.Location = new Point(0x23, 0x1ca);
            this.panelRbuttom.Name = "panelRbuttom";
            this.panelRbuttom.Size = new Size(0x2df, 0x8f);
            this.panelRbuttom.Style = StyleType.Fixed3D;
            this.panelRbuttom.TabIndex = 0xd3;
            this.neuSpread1.About = "3.0.2004.2005";
            this.neuSpread1.AccessibleDescription = "neuSpread1, Sheet1, Row 0, Column 0, ";
            this.neuSpread1.BackColor = Color.White;
            this.neuSpread1.FileName = "";
            this.neuSpread1.HorizontalScrollBarPolicy = ScrollBarPolicy.Never;
            this.neuSpread1.IsAutoSaveGridStatus = false;
            this.neuSpread1.IsCanCustomConfigColumn = false;
            this.neuSpread1.Location = new Point(0x59, 13);
            this.neuSpread1.Name = "neuSpread1";
            this.neuSpread1.Sheets.AddRange(new SheetView[] { this.neuSpread1_Sheet1 });
            this.neuSpread1.Size = new Size(560, 0x34);
            this.neuSpread1.Style = StyleType.Fixed3D;
            this.neuSpread1.TabIndex = 0x94;
            appearance.BackColor = SystemColors.Info;
            appearance.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            appearance.ForeColor = SystemColors.InfoText;
            this.neuSpread1.TextTipAppearance = appearance;
            this.neuSpread1.VerticalScrollBarPolicy = ScrollBarPolicy.Never;
            this.neuSpread1_Sheet1.Reset();
            this.neuSpread1_Sheet1.SheetName = "Sheet1";
            this.neuSpread1_Sheet1.ReferenceStyle = ReferenceStyle.R1C1;
            this.neuSpread1_Sheet1.ColumnCount = 1;
            this.neuSpread1_Sheet1.RowCount = 1;
            this.neuSpread1_Sheet1.ActiveSkin = new SheetSkin("CustomSkin1", Color.White, Color.Empty, Color.Empty, Color.LightGray, GridLines.Both, Color.Empty, Color.Empty, Color.Empty, Color.Empty, Color.Empty, Color.Empty, false, false, false, true, true);
            type.Multiline = true;
            type.WordWrap = true;
            this.neuSpread1_Sheet1.Cells.Get(0, 0).CellType = type;
            this.neuSpread1_Sheet1.Cells.Get(0, 0).Font = new Font("宋体", 10.5f);
            this.neuSpread1_Sheet1.ColumnHeader.Visible = false;
            this.neuSpread1_Sheet1.Columns.Get(0).Width = 558f;
            this.neuSpread1_Sheet1.PrintInfo.ShowBorder = false;
            this.neuSpread1_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.neuSpread1_Sheet1.RowHeader.DefaultStyle.Parent = "HeaderDefault";
            this.neuSpread1_Sheet1.RowHeader.Visible = false;
            this.neuSpread1_Sheet1.Rows.Get(0).Height = 51f;
            this.neuSpread1_Sheet1.VisualStyles = VisualStyles.Off;
            this.neuSpread1_Sheet1.ReferenceStyle = ReferenceStyle.A1;
            this.lbReportTime.AutoSize = true;
            this.lbReportTime.Font = new Font("宋体", 10.5f);
            this.lbReportTime.Location = new Point(0x1e7, 0x6c);
            this.lbReportTime.Name = "lbReportTime";
            this.lbReportTime.Size = new Size(70, 14);
            this.lbReportTime.Style = StyleType.Fixed3D;
            this.lbReportTime.TabIndex = 0x93;
            this.lbReportTime.Text = "neuLabel1";
            this.neuPanel6.BackColor = Color.Black;
            this.neuPanel6.Location = new Point(-1, 0x87);
            this.neuPanel6.Name = "neuPanel6";
            this.neuPanel6.Size = new Size(740, 2);
            this.neuPanel6.Style = StyleType.Fixed3D;
            this.neuPanel6.TabIndex = 0x92;
            this.neuPanel5.BackColor = Color.Black;
            this.neuPanel5.Location = new Point(-1, 3);
            this.neuPanel5.Name = "neuPanel5";
            this.neuPanel5.Size = new Size(740, 2);
            this.neuPanel5.Style = StyleType.Fixed3D;
            this.neuPanel5.TabIndex = 0x8f;
            this.lbDoctorDept.AutoSize = true;
            this.lbDoctorDept.Font = new Font("宋体", 10.5f);
            this.lbDoctorDept.Location = new Point(290, 0x6c);
            this.lbDoctorDept.Name = "lbDoctorDept";
            this.lbDoctorDept.Size = new Size(70, 14);
            this.lbDoctorDept.Style = StyleType.Fixed3D;
            this.lbDoctorDept.TabIndex = 0x91;
            this.lbDoctorDept.Text = "neuLabel2";
            this.lbReportDoctor.AutoSize = true;
            this.lbReportDoctor.Font = new Font("宋体", 10.5f);
            this.lbReportDoctor.Location = new Point(0x59, 0x6c);
            this.lbReportDoctor.Name = "lbReportDoctor";
            this.lbReportDoctor.Size = new Size(70, 14);
            this.lbReportDoctor.Style = StyleType.Fixed3D;
            this.lbReportDoctor.TabIndex = 0x90;
            this.lbReportDoctor.Text = "neuLabel2";
            this.lbCase.AutoSize = true;
            this.lbCase.Font = new Font("宋体", 10.5f);
            this.lbCase.Location = new Point(0x59, 0x4c);
            this.lbCase.Name = "lbCase";
            this.lbCase.Size = new Size(70, 14);
            this.lbCase.Style = StyleType.Fixed3D;
            this.lbCase.TabIndex = 0x8f;
            this.lbCase.Text = "neuLabel2";
            this.label35.AutoSize = true;
            this.label35.Font = new Font("宋体", 10.5f);
            this.label35.Location = new Point(12, 0x4c);
            this.label35.Name = "label35";
            this.label35.Size = new Size(0x4d, 14);
            this.label35.TabIndex = 0x72;
            this.label35.Text = "退卡原因：";
            this.label35.TextAlign = ContentAlignment.MiddleLeft;
            this.label9.AutoSize = true;
            this.label9.BackColor = Color.White;
            this.label9.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label9.Location = new Point(12, 8);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x31, 14);
            this.label9.TabIndex = 10;
            this.label9.Text = "备注：";
            this.label9.TextAlign = ContentAlignment.MiddleLeft;
            this.label37.AutoSize = true;
            this.label37.BackColor = Color.White;
            this.label37.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label37.Location = new Point(0x1a0, 0x6c);
            this.label37.Name = "label37";
            this.label37.Size = new Size(0x4d, 14);
            this.label37.TabIndex = 0x12;
            this.label37.Text = "填卡时间：";
            this.label37.TextAlign = ContentAlignment.MiddleLeft;
            this.label39.AutoSize = true;
            this.label39.BackColor = Color.White;
            this.label39.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label39.Location = new Point(0xd4, 0x6c);
            this.label39.Name = "label39";
            this.label39.Size = new Size(0x4d, 14);
            this.label39.TabIndex = 0x10;
            this.label39.Text = "报告科室：";
            this.label39.TextAlign = ContentAlignment.MiddleLeft;
            this.label41.AutoSize = true;
            this.label41.BackColor = Color.White;
            this.label41.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label41.Location = new Point(12, 0x6c);
            this.label41.Name = "label41";
            this.label41.Size = new Size(0x4d, 14);
            this.label41.TabIndex = 14;
            this.label41.Text = "报告医生：";
            this.label41.TextAlign = ContentAlignment.MiddleLeft;
            this.panelRtop3.BackColor = Color.White;
            this.panelRtop3.Controls.Add(this.lbDeadDate);
            this.panelRtop3.Controls.Add(this.lbDiaDate);
            this.panelRtop3.Controls.Add(this.lbInfectionDate);
            this.panelRtop3.Controls.Add(this.lbCaseClaseTwo);
            this.panelRtop3.Controls.Add(this.lbCaseClassOne);
            this.panelRtop3.Controls.Add(this.lbInfectionClass);
            this.panelRtop3.Controls.Add(this.lbDeadDateLable);
            this.panelRtop3.Controls.Add(this.rdbInfectionOtherNo);
            this.panelRtop3.Controls.Add(this.rdbInfectOtherYes);
            this.panelRtop3.Controls.Add(this.label42);
            this.panelRtop3.Controls.Add(this.label46);
            this.panelRtop3.Controls.Add(this.label47);
            this.panelRtop3.Controls.Add(this.label43);
            this.panelRtop3.Controls.Add(this.label48);
            this.panelRtop3.Location = new Point(0x23, 0x12e);
            this.panelRtop3.Name = "panelRtop3";
            this.panelRtop3.Size = new Size(0x2df, 150);
            this.panelRtop3.Style = StyleType.Fixed3D;
            this.panelRtop3.TabIndex = 210;
            this.lbDeadDate.AutoSize = true;
            this.lbDeadDate.Font = new Font("宋体", 10.5f);
            this.lbDeadDate.Location = new Point(0x1ab, 0x7d);
            this.lbDeadDate.Name = "lbDeadDate";
            this.lbDeadDate.Size = new Size(70, 14);
            this.lbDeadDate.Style = StyleType.Fixed3D;
            this.lbDeadDate.TabIndex = 0x8e;
            this.lbDeadDate.Text = "neuLabel2";
            this.lbDiaDate.AutoSize = true;
            this.lbDiaDate.Font = new Font("宋体", 10.5f);
            this.lbDiaDate.Location = new Point(0x59, 0x7d);
            this.lbDiaDate.Name = "lbDiaDate";
            this.lbDiaDate.Size = new Size(70, 14);
            this.lbDiaDate.Style = StyleType.Fixed3D;
            this.lbDiaDate.TabIndex = 0x8d;
            this.lbDiaDate.Text = "neuLabel2";
            this.lbInfectionDate.AutoSize = true;
            this.lbInfectionDate.Font = new Font("宋体", 10.5f);
            this.lbInfectionDate.Location = new Point(0x5c, 0x5c);
            this.lbInfectionDate.Name = "lbInfectionDate";
            this.lbInfectionDate.Size = new Size(70, 14);
            this.lbInfectionDate.Style = StyleType.Fixed3D;
            this.lbInfectionDate.TabIndex = 140;
            this.lbInfectionDate.Text = "neuLabel2";
            this.lbCaseClaseTwo.AutoSize = true;
            this.lbCaseClaseTwo.Font = new Font("宋体", 10.5f);
            this.lbCaseClaseTwo.Location = new Point(0x5c, 0x44);
            this.lbCaseClaseTwo.Name = "lbCaseClaseTwo";
            this.lbCaseClaseTwo.Size = new Size(70, 14);
            this.lbCaseClaseTwo.Style = StyleType.Fixed3D;
            this.lbCaseClaseTwo.TabIndex = 0x8b;
            this.lbCaseClaseTwo.Text = "neuLabel2";
            this.lbCaseClassOne.AutoSize = true;
            this.lbCaseClassOne.Font = new Font("宋体", 10.5f);
            this.lbCaseClassOne.Location = new Point(0x5c, 0x2d);
            this.lbCaseClassOne.Name = "lbCaseClassOne";
            this.lbCaseClassOne.Size = new Size(70, 14);
            this.lbCaseClassOne.Style = StyleType.Fixed3D;
            this.lbCaseClassOne.TabIndex = 0x8a;
            this.lbCaseClassOne.Text = "neuLabel2";
            this.lbInfectionClass.AutoSize = true;
            this.lbInfectionClass.Font = new Font("宋体", 10.5f);
            this.lbInfectionClass.Location = new Point(0x5c, 12);
            this.lbInfectionClass.Name = "lbInfectionClass";
            this.lbInfectionClass.Size = new Size(70, 14);
            this.lbInfectionClass.Style = StyleType.Fixed3D;
            this.lbInfectionClass.TabIndex = 0x89;
            this.lbInfectionClass.Text = "neuLabel2";
            this.lbDeadDateLable.AutoSize = true;
            this.lbDeadDateLable.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbDeadDateLable.Location = new Point(0x163, 0x7d);
            this.lbDeadDateLable.Name = "lbDeadDateLable";
            this.lbDeadDateLable.Size = new Size(70, 14);
            this.lbDeadDateLable.TabIndex = 0x53;
            this.lbDeadDateLable.Text = "死亡日期:";
            this.lbDeadDateLable.TextAlign = ContentAlignment.MiddleLeft;
            this.rdbInfectionOtherNo.Checked = true;
            this.rdbInfectionOtherNo.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rdbInfectionOtherNo.Location = new Point(0x213, 0x13);
            this.rdbInfectionOtherNo.Name = "rdbInfectionOtherNo";
            this.rdbInfectionOtherNo.Size = new Size(0x30, 0x18);
            this.rdbInfectionOtherNo.TabIndex = 0x47;
            this.rdbInfectionOtherNo.TabStop = true;
            this.rdbInfectionOtherNo.Text = "无";
            this.rdbInfectOtherYes.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rdbInfectOtherYes.Location = new Point(0x1c9, 0x13);
            this.rdbInfectOtherYes.Name = "rdbInfectOtherYes";
            this.rdbInfectOtherYes.Size = new Size(0x38, 0x18);
            this.rdbInfectOtherYes.TabIndex = 0x45;
            this.rdbInfectOtherYes.Text = "有";
            this.label42.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label42.Location = new Point(0x163, 12);
            this.label42.Name = "label42";
            this.label42.Size = new Size(0x60, 0x26);
            this.label42.TabIndex = 0x42;
            this.label42.Text = "密切接触者有无相同症状：";
            this.label42.TextAlign = ContentAlignment.MiddleLeft;
            this.label46.AutoSize = true;
            this.label46.BackColor = Color.White;
            this.label46.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label46.Location = new Point(12, 0x7d);
            this.label46.Name = "label46";
            this.label46.Size = new Size(0x4d, 14);
            this.label46.TabIndex = 0x4f;
            this.label46.Text = "诊断时间：";
            this.label46.TextAlign = ContentAlignment.MiddleLeft;
            this.label47.AutoSize = true;
            this.label47.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label47.Location = new Point(12, 0x5c);
            this.label47.Name = "label47";
            this.label47.Size = new Size(0x4d, 14);
            this.label47.TabIndex = 0x4c;
            this.label47.Text = "发病日期：";
            this.label47.TextAlign = ContentAlignment.MiddleLeft;
            this.label43.AutoSize = true;
            this.label43.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label43.Location = new Point(12, 0x2d);
            this.label43.Name = "label43";
            this.label43.Size = new Size(0x4d, 14);
            this.label43.TabIndex = 0x3f;
            this.label43.Text = "病例分类：";
            this.label43.TextAlign = ContentAlignment.MiddleLeft;
            this.label48.AutoSize = true;
            this.label48.BackColor = Color.White;
            this.label48.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label48.Location = new Point(12, 12);
            this.label48.Name = "label48";
            this.label48.Size = new Size(0x4d, 14);
            this.label48.TabIndex = 0x3d;
            this.label48.Text = "疾病名称：";
            this.label48.TextAlign = ContentAlignment.MiddleLeft;
            this.panelRtop2.BackColor = Color.White;
            this.panelRtop2.Controls.Add(this.neuPanel4);
            this.panelRtop2.Controls.Add(this.lbWorkPlace);
            this.panelRtop2.Controls.Add(this.lbProfession);
            this.panelRtop2.Controls.Add(this.lbTelephone);
            this.panelRtop2.Controls.Add(this.lbSpecificlAddress);
            this.panelRtop2.Controls.Add(this.lbAge);
            this.panelRtop2.Controls.Add(this.lbBirthday);
            this.panelRtop2.Controls.Add(this.lbPatientID);
            this.panelRtop2.Controls.Add(this.lbSex);
            this.panelRtop2.Controls.Add(this.lbPatientParents);
            this.panelRtop2.Controls.Add(this.lbPatientName);
            this.panelRtop2.Controls.Add(this.neuPanel1);
            this.panelRtop2.Controls.Add(this.label1);
            this.panelRtop2.Controls.Add(this.label49);
            this.panelRtop2.Controls.Add(this.label13);
            this.panelRtop2.Controls.Add(this.label8);
            this.panelRtop2.Controls.Add(this.label7);
            this.panelRtop2.Controls.Add(this.rdbDay);
            this.panelRtop2.Controls.Add(this.rdbMonth);
            this.panelRtop2.Controls.Add(this.rdbYear);
            this.panelRtop2.Controls.Add(this.label59);
            this.panelRtop2.Controls.Add(this.label60);
            this.panelRtop2.Controls.Add(this.labless);
            this.panelRtop2.Controls.Add(this.label64);
            this.panelRtop2.Controls.Add(this.label61);
            this.panelRtop2.Controls.Add(this.label63);
            this.panelRtop2.Controls.Add(this.label65);
            this.panelRtop2.Location = new Point(0x23, 0x55);
            this.panelRtop2.Name = "panelRtop2";
            this.panelRtop2.Size = new Size(0x2df, 0xd9);
            this.panelRtop2.Style = StyleType.Fixed3D;
            this.panelRtop2.TabIndex = 0xd1;
            this.neuPanel4.BackColor = Color.Black;
            this.neuPanel4.Location = new Point(-1, 0xd4);
            this.neuPanel4.Name = "neuPanel4";
            this.neuPanel4.Size = new Size(740, 2);
            this.neuPanel4.Style = StyleType.Fixed3D;
            this.neuPanel4.TabIndex = 0x8a;
            this.lbWorkPlace.AutoSize = true;
            this.lbWorkPlace.Font = new Font("宋体", 10.5f);
            this.lbWorkPlace.Location = new Point(0x62, 0xb0);
            this.lbWorkPlace.Name = "lbWorkPlace";
            this.lbWorkPlace.Size = new Size(70, 14);
            this.lbWorkPlace.Style = StyleType.Fixed3D;
            this.lbWorkPlace.TabIndex = 0x88;
            this.lbWorkPlace.Text = "neuLabel2";
            this.lbProfession.AutoSize = true;
            this.lbProfession.Font = new Font("宋体", 10.5f);
            this.lbProfession.Location = new Point(0x1ab, 150);
            this.lbProfession.Name = "lbProfession";
            this.lbProfession.Size = new Size(70, 14);
            this.lbProfession.Style = StyleType.Fixed3D;
            this.lbProfession.TabIndex = 0x87;
            this.lbProfession.Text = "neuLabel2";
            this.lbTelephone.AutoSize = true;
            this.lbTelephone.Font = new Font("宋体", 10.5f);
            this.lbTelephone.Location = new Point(0x62, 150);
            this.lbTelephone.Name = "lbTelephone";
            this.lbTelephone.Size = new Size(70, 14);
            this.lbTelephone.Style = StyleType.Fixed3D;
            this.lbTelephone.TabIndex = 0x86;
            this.lbTelephone.Text = "neuLabel2";
            this.lbSpecificlAddress.AutoSize = true;
            this.lbSpecificlAddress.Font = new Font("宋体", 10.5f);
            this.lbSpecificlAddress.Location = new Point(0x72, 0x7b);
            this.lbSpecificlAddress.Name = "lbSpecificlAddress";
            this.lbSpecificlAddress.Size = new Size(70, 14);
            this.lbSpecificlAddress.Style = StyleType.Fixed3D;
            this.lbSpecificlAddress.TabIndex = 0x85;
            this.lbSpecificlAddress.Text = "neuLabel2";
            this.lbAge.AutoSize = true;
            this.lbAge.Font = new Font("宋体", 10.5f);
            this.lbAge.Location = new Point(0x1a8, 0x40);
            this.lbAge.Name = "lbAge";
            this.lbAge.Size = new Size(70, 14);
            this.lbAge.Style = StyleType.Fixed3D;
            this.lbAge.TabIndex = 0x84;
            this.lbAge.Text = "neuLabel2";
            this.lbBirthday.AutoSize = true;
            this.lbBirthday.Font = new Font("宋体", 10.5f);
            this.lbBirthday.Location = new Point(0x5e, 0x40);
            this.lbBirthday.Name = "lbBirthday";
            this.lbBirthday.Size = new Size(70, 14);
            this.lbBirthday.Style = StyleType.Fixed3D;
            this.lbBirthday.TabIndex = 0x83;
            this.lbBirthday.Text = "neuLabel1";
            this.lbPatientID.AutoSize = true;
            this.lbPatientID.Font = new Font("宋体", 10.5f);
            this.lbPatientID.Location = new Point(0x5e, 0x22);
            this.lbPatientID.Name = "lbPatientID";
            this.lbPatientID.Size = new Size(70, 14);
            this.lbPatientID.Style = StyleType.Fixed3D;
            this.lbPatientID.TabIndex = 130;
            this.lbPatientID.Text = "neuLabel1";
            this.lbSex.AutoSize = true;
            this.lbSex.Font = new Font("宋体", 10.5f);
            this.lbSex.Location = new Point(0x1a8, 0x22);
            this.lbSex.Name = "lbSex";
            this.lbSex.Size = new Size(70, 14);
            this.lbSex.Style = StyleType.Fixed3D;
            this.lbSex.TabIndex = 0x81;
            this.lbSex.Text = "neuLabel1";
            this.lbPatientParents.AutoSize = true;
            this.lbPatientParents.Font = new Font("宋体", 10.5f);
            this.lbPatientParents.Location = new Point(0x1a8, 7);
            this.lbPatientParents.Name = "lbPatientParents";
            this.lbPatientParents.Size = new Size(70, 14);
            this.lbPatientParents.Style = StyleType.Fixed3D;
            this.lbPatientParents.TabIndex = 0x80;
            this.lbPatientParents.Text = "neuLabel1";
            this.lbPatientName.AutoSize = true;
            this.lbPatientName.Font = new Font("宋体", 10.5f);
            this.lbPatientName.Location = new Point(0x5e, 7);
            this.lbPatientName.Name = "lbPatientName";
            this.lbPatientName.Size = new Size(70, 14);
            this.lbPatientName.Style = StyleType.Fixed3D;
            this.lbPatientName.TabIndex = 0x7f;
            this.lbPatientName.Text = "neuLabel1";
            this.neuPanel1.Controls.Add(this.cbxHomeAearTwo);
            this.neuPanel1.Controls.Add(this.cbxHomeAearOne);
            this.neuPanel1.Controls.Add(this.cbxHomeAearThree);
            this.neuPanel1.Controls.Add(this.cbxHomeAearFour);
            this.neuPanel1.Controls.Add(this.cbxHomeAearFive);
            this.neuPanel1.Controls.Add(this.cbxHomeAearSix);
            this.neuPanel1.Location = new Point(0x5b, 0x5d);
            this.neuPanel1.Name = "neuPanel1";
            this.neuPanel1.Size = new Size(0x218, 0x17);
            this.neuPanel1.Style = StyleType.Fixed3D;
            this.neuPanel1.TabIndex = 0x70;
            this.cbxHomeAearTwo.AutoSize = true;
            this.cbxHomeAearTwo.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cbxHomeAearTwo.ForeColor = Color.Black;
            this.cbxHomeAearTwo.Location = new Point(0x55, 3);
            this.cbxHomeAearTwo.Name = "cbxHomeAearTwo";
            this.cbxHomeAearTwo.Size = new Size(0x5f, 0x12);
            this.cbxHomeAearTwo.TabIndex = 0x42;
            this.cbxHomeAearTwo.Tag = "2";
            this.cbxHomeAearTwo.Text = "本市其它区";
            this.cbxHomeAearOne.AutoSize = true;
            this.cbxHomeAearOne.Checked = true;
            this.cbxHomeAearOne.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cbxHomeAearOne.ForeColor = Color.Black;
            this.cbxHomeAearOne.Location = new Point(13, 3);
            this.cbxHomeAearOne.Name = "cbxHomeAearOne";
            this.cbxHomeAearOne.Size = new Size(0x35, 0x12);
            this.cbxHomeAearOne.TabIndex = 0x42;
            this.cbxHomeAearOne.TabStop = true;
            this.cbxHomeAearOne.Tag = "1";
            this.cbxHomeAearOne.Text = "本区";
            this.cbxHomeAearThree.AutoSize = true;
            this.cbxHomeAearThree.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cbxHomeAearThree.ForeColor = Color.Black;
            this.cbxHomeAearThree.Location = new Point(0xc9, 3);
            this.cbxHomeAearThree.Name = "cbxHomeAearThree";
            this.cbxHomeAearThree.Size = new Size(0x5f, 0x12);
            this.cbxHomeAearThree.TabIndex = 0x43;
            this.cbxHomeAearThree.Tag = "3";
            this.cbxHomeAearThree.Text = "本省其它市";
            this.cbxHomeAearFour.AutoSize = true;
            this.cbxHomeAearFour.BackColor = Color.White;
            this.cbxHomeAearFour.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cbxHomeAearFour.ForeColor = Color.Black;
            this.cbxHomeAearFour.Location = new Point(0x13d, 3);
            this.cbxHomeAearFour.Name = "cbxHomeAearFour";
            this.cbxHomeAearFour.Size = new Size(0x43, 0x12);
            this.cbxHomeAearFour.TabIndex = 0x44;
            this.cbxHomeAearFour.Tag = "4";
            this.cbxHomeAearFour.Text = "其他省";
            this.cbxHomeAearFour.UseVisualStyleBackColor = false;
            this.cbxHomeAearFive.AutoSize = true;
            this.cbxHomeAearFive.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cbxHomeAearFive.ForeColor = Color.Black;
            this.cbxHomeAearFive.Location = new Point(0x183, 3);
            this.cbxHomeAearFive.Name = "cbxHomeAearFive";
            this.cbxHomeAearFive.Size = new Size(0x43, 0x12);
            this.cbxHomeAearFive.TabIndex = 0x45;
            this.cbxHomeAearFive.Tag = "5";
            this.cbxHomeAearFive.Text = "港澳台";
            this.cbxHomeAearSix.AutoSize = true;
            this.cbxHomeAearSix.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.cbxHomeAearSix.ForeColor = Color.Black;
            this.cbxHomeAearSix.Location = new Point(0x1ca, 3);
            this.cbxHomeAearSix.Name = "cbxHomeAearSix";
            this.cbxHomeAearSix.Size = new Size(0x35, 0x12);
            this.cbxHomeAearSix.TabIndex = 70;
            this.cbxHomeAearSix.Tag = "6";
            this.cbxHomeAearSix.Text = "外籍";
            this.label1.AutoSize = true;
            this.label1.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label1.Location = new Point(12, 0x7b);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x69, 14);
            this.label1.TabIndex = 0x7a;
            this.label1.Text = "现住详细地址：";
            this.label1.TextAlign = ContentAlignment.MiddleLeft;
            this.label49.AutoSize = true;
            this.label49.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label49.Location = new Point(0x17b, 150);
            this.label49.Name = "label49";
            this.label49.Size = new Size(0x2a, 14);
            this.label49.TabIndex = 0x6c;
            this.label49.Text = "职业:";
            this.label49.TextAlign = ContentAlignment.MiddleLeft;
            this.label13.AutoSize = true;
            this.label13.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label13.Location = new Point(12, 150);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x4d, 14);
            this.label13.TabIndex = 0x7b;
            this.label13.Text = "联系电话：";
            this.label13.TextAlign = ContentAlignment.MiddleLeft;
            this.label8.AutoSize = true;
            this.label8.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label8.Location = new Point(12, 0xb0);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x4d, 14);
            this.label8.TabIndex = 0x7e;
            this.label8.Text = "工作单位：";
            this.label8.TextAlign = ContentAlignment.MiddleLeft;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label7.Location = new Point(12, 0x61);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x4d, 14);
            this.label7.TabIndex = 120;
            this.label7.Text = "现住地址：";
            this.label7.TextAlign = ContentAlignment.MiddleLeft;
            this.rdbDay.AutoSize = true;
            this.rdbDay.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rdbDay.Location = new Point(0x282, 0x3e);
            this.rdbDay.Name = "rdbDay";
            this.rdbDay.Size = new Size(0x35, 0x12);
            this.rdbDay.TabIndex = 0x3d;
            this.rdbDay.Text = "天）";
            this.rdbMonth.AutoSize = true;
            this.rdbMonth.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rdbMonth.Location = new Point(0x260, 0x3e);
            this.rdbMonth.Name = "rdbMonth";
            this.rdbMonth.Size = new Size(0x27, 0x12);
            this.rdbMonth.TabIndex = 60;
            this.rdbMonth.Text = "月";
            this.rdbYear.AutoSize = true;
            this.rdbYear.Checked = true;
            this.rdbYear.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.rdbYear.Location = new Point(0x23b, 0x3e);
            this.rdbYear.Name = "rdbYear";
            this.rdbYear.Size = new Size(0x27, 0x12);
            this.rdbYear.TabIndex = 0x3b;
            this.rdbYear.TabStop = true;
            this.rdbYear.Text = "岁";
            this.label59.AutoSize = true;
            this.label59.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label59.Location = new Point(0x1e8, 0x40);
            this.label59.Name = "label59";
            this.label59.Size = new Size(0x5b, 14);
            this.label59.TabIndex = 0x76;
            this.label59.Text = "（年龄单位：";
            this.label59.TextAlign = ContentAlignment.MiddleLeft;
            this.label60.AutoSize = true;
            this.label60.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label60.Location = new Point(0x132, 0x40);
            this.label60.Name = "label60";
            this.label60.Size = new Size(0x70, 14);
            this.label60.TabIndex = 0x75;
            this.label60.Text = "生日不详填年龄:";
            this.label60.TextAlign = ContentAlignment.MiddleLeft;
            this.labless.AutoSize = true;
            this.labless.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.labless.Location = new Point(0x178, 0x22);
            this.labless.Name = "labless";
            this.labless.Size = new Size(0x2a, 14);
            this.labless.TabIndex = 0x3f;
            this.labless.Text = "性别:";
            this.labless.TextAlign = ContentAlignment.MiddleLeft;
            this.label64.AutoSize = true;
            this.label64.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label64.Location = new Point(320, 7);
            this.label64.Name = "label64";
            this.label64.Size = new Size(0x62, 14);
            this.label64.TabIndex = 110;
            this.label64.Text = "患儿家长姓名:";
            this.label64.TextAlign = ContentAlignment.MiddleLeft;
            this.label61.AutoSize = true;
            this.label61.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label61.Location = new Point(12, 0x40);
            this.label61.Name = "label61";
            this.label61.Size = new Size(0x4d, 14);
            this.label61.TabIndex = 0x73;
            this.label61.Text = "出生日期：";
            this.label61.TextAlign = ContentAlignment.MiddleLeft;
            this.label63.AutoSize = true;
            this.label63.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label63.Location = new Point(12, 7);
            this.label63.Name = "label63";
            this.label63.Size = new Size(0x4d, 14);
            this.label63.TabIndex = 0x6b;
            this.label63.Text = "患者姓名：";
            this.label63.TextAlign = ContentAlignment.MiddleLeft;
            this.label65.AutoSize = true;
            this.label65.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label65.Location = new Point(12, 0x22);
            this.label65.Name = "label65";
            this.label65.Size = new Size(0x4d, 14);
            this.label65.TabIndex = 0x2d;
            this.label65.Text = "身份证号：";
            this.label65.TextAlign = ContentAlignment.MiddleLeft;
            this.panelRtop1.BackColor = Color.White;
            this.panelRtop1.Controls.Add(this.lbClinicNO);
            this.panelRtop1.Controls.Add(this.lbID);
            this.panelRtop1.Controls.Add(this.lbState);
            this.panelRtop1.Controls.Add(this.neuPanel3);
            this.panelRtop1.Controls.Add(this.labelClinic);
            this.panelRtop1.Controls.Add(this.label68);
            this.panelRtop1.Controls.Add(this.label66);
            this.panelRtop1.Controls.Add(this.label69);
            this.panelRtop1.ForeColor = Color.Black;
            this.panelRtop1.Location = new Point(0x23, 3);
            this.panelRtop1.Name = "panelRtop1";
            this.panelRtop1.Size = new Size(0x2df, 0x4f);
            this.panelRtop1.Style = StyleType.Fixed3D;
            this.panelRtop1.TabIndex = 0xd0;
            this.lbClinicNO.AutoSize = true;
            this.lbClinicNO.Font = new Font("宋体", 10.5f);
            this.lbClinicNO.Location = new Point(530, 0x30);
            this.lbClinicNO.Name = "lbClinicNO";
            this.lbClinicNO.Size = new Size(70, 14);
            this.lbClinicNO.Style = StyleType.Fixed3D;
            this.lbClinicNO.TabIndex = 0x8d;
            this.lbClinicNO.Text = "neuLabel1";
            this.lbID.AutoSize = true;
            this.lbID.Font = new Font("宋体", 10.5f);
            this.lbID.Location = new Point(0x142, 0x30);
            this.lbID.Name = "lbID";
            this.lbID.Size = new Size(70, 14);
            this.lbID.Style = StyleType.Fixed3D;
            this.lbID.TabIndex = 140;
            this.lbID.Text = "neuLabel1";
            this.lbState.AutoSize = true;
            this.lbState.Font = new Font("宋体", 10.5f);
            this.lbState.Location = new Point(70, 0x30);
            this.lbState.Name = "lbState";
            this.lbState.Size = new Size(70, 14);
            this.lbState.Style = StyleType.Fixed3D;
            this.lbState.TabIndex = 0x8b;
            this.lbState.Text = "neuLabel1";
            this.neuPanel3.BackColor = Color.Black;
            this.neuPanel3.Location = new Point(-1, 0x48);
            this.neuPanel3.Name = "neuPanel3";
            this.neuPanel3.Size = new Size(740, 2);
            this.neuPanel3.Style = StyleType.Fixed3D;
            this.neuPanel3.TabIndex = 0x8a;
            this.labelClinic.AutoSize = true;
            this.labelClinic.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.labelClinic.Location = new Point(0x1da, 0x30);
            this.labelClinic.Name = "labelClinic";
            this.labelClinic.Size = new Size(0x3f, 14);
            this.labelClinic.TabIndex = 0x69;
            this.labelClinic.Text = "病历号：";
            this.labelClinic.TextAlign = ContentAlignment.MiddleCenter;
            this.label68.AutoSize = true;
            this.label68.Font = new Font("宋体", 10.5f);
            this.label68.Location = new Point(0x100, 0x30);
            this.label68.Name = "label68";
            this.label68.Size = new Size(0x4d, 14);
            this.label68.TabIndex = 0x67;
            this.label68.Text = "卡片编号：";
            this.label68.TextAlign = ContentAlignment.MiddleLeft;
            this.label66.AutoSize = true;
            this.label66.BackColor = Color.White;
            this.label66.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.label66.Location = new Point(3, 0x30);
            this.label66.Name = "label66";
            this.label66.Size = new Size(0x4d, 14);
            this.label66.TabIndex = 4;
            this.label66.Text = "报卡类型: ";
            this.label66.TextAlign = ContentAlignment.BottomLeft;
            this.label69.AutoSize = true;
            this.label69.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.label69.Location = new Point(0xe7, 13);
            this.label69.Name = "label69";
            this.label69.Size = new Size(0x11a, 20);
            this.label69.TabIndex = 100;
            this.label69.Text = "中华人民共和国传染病报告卡";
            this.label69.TextAlign = ContentAlignment.MiddleLeft;
            this.neuPanel2.BackColor = Color.Black;
            this.neuPanel2.Location = new Point(770, 0x4a);
            this.neuPanel2.Name = "neuPanel2";
            this.neuPanel2.Size = new Size(2, 0x20c);
            this.neuPanel2.Style = StyleType.Fixed3D;
            this.neuPanel2.TabIndex = 0xd4;
            this.neuPanel7.BackColor = Color.Black;
            this.neuPanel7.Location = new Point(0x21, 0x4a);
            this.neuPanel7.Name = "neuPanel7";
            this.neuPanel7.Size = new Size(2, 0x20c);
            this.neuPanel7.Style = StyleType.Fixed3D;
            this.neuPanel7.TabIndex = 0xd5;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            this.BackColor = Color.White;
            base.Controls.Add(this.neuPanel7);
            base.Controls.Add(this.neuPanel2);
            base.Controls.Add(this.panelRbuttom);
            base.Controls.Add(this.panelRtop3);
            base.Controls.Add(this.panelRtop2);
            base.Controls.Add(this.panelRtop1);
            base.Name = "ucPrint";
            base.Size = new Size(0x326, 0x269);
            this.panelRbuttom.ResumeLayout(false);
            this.panelRbuttom.PerformLayout();
            ((ISupportInitialize) this.neuSpread1).EndInit();
            ((ISupportInitialize) this.neuSpread1_Sheet1).EndInit();
            this.panelRtop3.ResumeLayout(false);
            this.panelRtop3.PerformLayout();
            this.panelRtop2.ResumeLayout(false);
            this.panelRtop2.PerformLayout();
            this.neuPanel1.ResumeLayout(false);
            this.neuPanel1.PerformLayout();
            this.panelRtop1.ResumeLayout(false);
            this.panelRtop1.PerformLayout();
            base.ResumeLayout(false);
        }
    }
}

