using BarcodeLib;
using FarPoint.Win;
using FarPoint.Win.Spread;
using FarPoint.Win.Spread.CellType;
using FarPoint.Win.Spread.Model;
using Neusoft.FrameWork.WinForms.Classes;
using Neusoft.FrameWork.WinForms.Controls;
using Neusoft.SOC.Local.Nurse.Properties;
using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;
using ThoughtWorks.QRCode.Codec;
namespace Neusoft.SOC.Local.Nurse.ShenZhen
{
    partial class ucPrintInjectScoutCard
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            TipAppearance appearance = new TipAppearance();
            ComplexBorder border = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border2 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border3 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border4 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border5 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border6 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border7 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border8 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border9 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border10 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border11 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border12 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border13 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border14 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border15 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border16 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border17 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border18 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border19 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border20 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border21 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border22 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border23 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border24 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border25 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border26 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border27 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border28 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border29 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border30 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border31 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border32 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border33 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border34 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border35 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border36 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border37 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border38 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border39 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border40 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border41 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border42 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border43 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border44 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border45 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border46 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border47 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border48 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border49 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border50 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border51 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border52 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border53 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border54 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border55 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.None), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            ComplexBorder border56 = new ComplexBorder(new ComplexBorderSide(ComplexBorderSideStyle.None, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.None, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black), new ComplexBorderSide(ComplexBorderSideStyle.ThinLine, Color.Black));
            BevelBorder border57 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, Color.Black);
            BevelBorder border58 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, SystemColors.ActiveCaptionText, 1, false, true, true, true);
            BevelBorder border59 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, Color.Black, 1, false, true, true, true);
            BevelBorder border60 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, Color.Black, 1, false, true, true, true);
            BevelBorder border61 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, Color.Black, 1, false, true, true, true);
            BevelBorder border62 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, Color.Black, 1, false, true, true, true);
            BevelBorder border63 = new BevelBorder(BevelBorderType.Raised, SystemColors.ActiveCaptionText, Color.Black, 1, false, true, true, true);
            TextCellType type = new TextCellType();
            TextCellType type2 = new TextCellType();
            TextCellType type3 = new TextCellType();
            TextCellType type4 = new TextCellType();
            this.neuPanel2 = new NeuPanel();
            this.nlbPageNo = new NeuLabel();
            this.neuPanel3 = new NeuPanel();
            this.neuPictureBox3 = new NeuPictureBox();
            this.neuPictureBox2 = new NeuPictureBox();
            this.neuLabel4 = new NeuLabel();
            this.lbTime = new NeuLabel();
            this.lbSex = new NeuLabel();
            this.neuLabel6 = new NeuLabel();
            this.neuLbDoct = new NeuLabel();
            this.lbAge = new NeuLabel();
            this.lblDiag = new NeuLabel();
            this.lblTitle = new NeuLabel();
            this.neuLabel9 = new NeuLabel();
            this.neuLabel12 = new NeuLabel();
            this.lbName = new NeuLabel();
            this.neuLabel2 = new NeuLabel();
            this.neuPictureBox1 = new NeuPictureBox();
            this.neuLabel8 = new NeuLabel();
            this.neuLabel10 = new NeuLabel();
            this.neuLabel3 = new NeuLabel();
            this.neuPanel1 = new NeuPanel();
            this.neuPanel4 = new NeuPanel();
            this.neuSpread1 = new NeuSpread();
            this.neuSpread1_Sheet1 = new SheetView();
            this.panel1 = new Panel();
            this.neuLabel5 = new NeuLabel();
            this.neuPanel2.SuspendLayout();
            this.neuPanel3.SuspendLayout();
            ((ISupportInitialize)this.neuPictureBox3).BeginInit();
            ((ISupportInitialize)this.neuPictureBox2).BeginInit();
            ((ISupportInitialize)this.neuPictureBox1).BeginInit();
            this.neuPanel1.SuspendLayout();
            this.neuPanel4.SuspendLayout();
            ((ISupportInitialize)this.neuSpread1).BeginInit();
            ((ISupportInitialize)this.neuSpread1_Sheet1).BeginInit();
            this.panel1.SuspendLayout();
            base.SuspendLayout();
            this.neuPanel2.BackColor = Color.White;
            this.neuPanel2.Controls.Add(this.nlbPageNo);
            this.neuPanel2.Controls.Add(this.neuPanel3);
            this.neuPanel2.Dock = DockStyle.Top;
            this.neuPanel2.Location = new Point(0, 0);
            this.neuPanel2.Name = "neuPanel2";
            this.neuPanel2.Size = new Size(0x2cc, 0x8b);
            this.neuPanel2.Style = StyleType.Fixed3D;
            this.neuPanel2.TabIndex = 1;
            this.nlbPageNo.AutoSize = true;
            this.nlbPageNo.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.nlbPageNo.Location = new Point(0x288, 9);
            this.nlbPageNo.Name = "nlbPageNo";
            this.nlbPageNo.Size = new Size(0x40, 0x10);
            this.nlbPageNo.Style = StyleType.Fixed3D;
            this.nlbPageNo.TabIndex = 0x11;
            this.nlbPageNo.Text = "页：1/5";
            this.nlbPageNo.Visible = false;
            this.neuPanel3.Controls.Add(this.neuPictureBox3);
            this.neuPanel3.Controls.Add(this.neuPictureBox2);
            this.neuPanel3.Controls.Add(this.neuLabel4);
            this.neuPanel3.Controls.Add(this.lbTime);
            this.neuPanel3.Controls.Add(this.lbSex);
            this.neuPanel3.Controls.Add(this.neuLabel6);
            this.neuPanel3.Controls.Add(this.neuLbDoct);
            this.neuPanel3.Controls.Add(this.lbAge);
            this.neuPanel3.Controls.Add(this.lblDiag);
            this.neuPanel3.Controls.Add(this.lblTitle);
            this.neuPanel3.Controls.Add(this.neuLabel9);
            this.neuPanel3.Controls.Add(this.neuLabel12);
            this.neuPanel3.Controls.Add(this.lbName);
            this.neuPanel3.Controls.Add(this.neuLabel2);
            this.neuPanel3.Controls.Add(this.neuPictureBox1);
            this.neuPanel3.Controls.Add(this.neuLabel8);
            this.neuPanel3.Controls.Add(this.neuLabel10);
            this.neuPanel3.Controls.Add(this.neuLabel3);
            this.neuPanel3.Location = new Point(0x53, 3);
            this.neuPanel3.Name = "neuPanel3";
            this.neuPanel3.Size = new Size(540, 0x89);
            this.neuPanel3.Style = StyleType.Fixed3D;
            this.neuPanel3.TabIndex = 0x69;
//            this.neuPictureBox3.Image = Resources.logo4;
            this.neuPictureBox3.Location = new Point(0x16, 2);
            this.neuPictureBox3.Name = "neuPictureBox3";
            this.neuPictureBox3.Size = new Size(0x2a, 0x29);
            this.neuPictureBox3.Style = StyleType.Fixed3D;
            this.neuPictureBox3.TabIndex = 0x69;
            this.neuPictureBox3.TabStop = false;
            this.neuPictureBox2.Location = new Point(0x17, 0x2c);
            this.neuPictureBox2.Name = "neuPictureBox2";
            this.neuPictureBox2.Size = new Size(60, 0x30);
            this.neuPictureBox2.Style = StyleType.Fixed3D;
            this.neuPictureBox2.TabIndex = 0x67;
            this.neuPictureBox2.TabStop = false;
            this.neuPictureBox2.Click += new EventHandler(this.neuPictureBox2_Click);
            this.neuLabel4.AutoSize = true;
            this.neuLabel4.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel4.Location = new Point(0x156, 0x6a);
            this.neuLabel4.Name = "neuLabel4";
            this.neuLabel4.Size = new Size(0x31, 14);
            this.neuLabel4.Style = StyleType.Fixed3D;
            this.neuLabel4.TabIndex = 0x68;
            this.neuLabel4.Text = "序号：";
            this.lbTime.AutoSize = true;
            this.lbTime.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbTime.Location = new Point(0x185, 0x47);
            this.lbTime.Name = "lbTime";
            this.lbTime.Size = new Size(0x85, 14);
            this.lbTime.Style = StyleType.Fixed3D;
            this.lbTime.TabIndex = 10;
            this.lbTime.Text = "2011-9-22 14:16:30";
            this.lbSex.AutoSize = true;
            this.lbSex.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbSex.Location = new Point(0x1d0, 0x29);
            this.lbSex.Name = "lbSex";
            this.lbSex.Size = new Size(40, 0x10);
            this.lbSex.Style = StyleType.Fixed3D;
            this.lbSex.TabIndex = 8;
            this.lbSex.Text = "----";
            this.neuLabel6.AutoSize = true;
            this.neuLabel6.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel6.Location = new Point(0x156, 0x29);
            this.neuLabel6.Name = "neuLabel6";
            this.neuLabel6.Size = new Size(0x31, 14);
            this.neuLabel6.Style = StyleType.Fixed3D;
            this.neuLabel6.TabIndex = 5;
            this.neuLabel6.Text = "年龄：";
            this.neuLbDoct.AutoSize = true;
            this.neuLbDoct.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLbDoct.Location = new Point(0x110, 0x6a);
            this.neuLbDoct.Name = "neuLbDoct";
            this.neuLbDoct.Size = new Size(0x38, 14);
            this.neuLbDoct.Style = StyleType.Fixed3D;
            this.neuLbDoct.TabIndex = 12;
            this.neuLbDoct.Text = "张志和B";
            this.lbAge.AutoSize = true;
            this.lbAge.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbAge.Location = new Point(0x184, 0x29);
            this.lbAge.Name = "lbAge";
            this.lbAge.Size = new Size(40, 0x10);
            this.lbAge.Style = StyleType.Fixed3D;
            this.lbAge.TabIndex = 6;
            this.lbAge.Text = "85岁";
            this.lblDiag.AutoSize = true;
            this.lblDiag.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lblDiag.Location = new Point(0x43, 0x68);
            this.lblDiag.Name = "lblDiag";
            this.lblDiag.Size = new Size(0x38, 0x10);
            this.lblDiag.Style = StyleType.Fixed3D;
            this.lblDiag.TabIndex = 0x13;
            this.lblDiag.Text = "高血压";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new Font("宋体", 15f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lblTitle.Location = new Point(0x3d, 13);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new Size(0x18e, 20);
            this.lblTitle.Style = StyleType.Fixed3D;
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "香港大学深圳医院 静脉输液（血）巡视卡";
            this.lblTitle.TextAlign = ContentAlignment.MiddleCenter;
            this.neuLabel9.AutoSize = true;
            this.neuLabel9.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel9.Location = new Point(10, 0x68);
            this.neuLabel9.Name = "neuLabel9";
            this.neuLabel9.Size = new Size(0x38, 0x10);
            this.neuLabel9.Style = StyleType.Fixed3D;
            this.neuLabel9.TabIndex = 0x12;
            this.neuLabel9.Text = "诊断：";
            this.neuLabel12.AutoSize = true;
            this.neuLabel12.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel12.Location = new Point(0xe0, 0x47);
            this.neuLabel12.Name = "neuLabel12";
            this.neuLabel12.Size = new Size(0x4d, 14);
            this.neuLabel12.Style = StyleType.Fixed3D;
            this.neuLabel12.TabIndex = 0x66;
            this.neuLabel12.Text = "药品组数：";
            this.lbName.AutoSize = true;
            this.lbName.Font = new Font("宋体", 12f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.lbName.Location = new Point(0x113, 0x29);
            this.lbName.Name = "lbName";
            this.lbName.Size = new Size(0x2a, 0x10);
            this.lbName.Style = StyleType.Fixed3D;
            this.lbName.TabIndex = 2;
            this.lbName.Text = "默罕";
            this.neuLabel2.AutoSize = true;
            this.neuLabel2.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel2.Location = new Point(0xe0, 0x29);
            this.neuLabel2.Name = "neuLabel2";
            this.neuLabel2.Size = new Size(0x31, 14);
            this.neuLabel2.Style = StyleType.Fixed3D;
            this.neuLabel2.TabIndex = 1;
            this.neuLabel2.Text = "姓名：";
            this.neuPictureBox1.ImageLocation = "";
            this.neuPictureBox1.Location = new Point(0x57, 0x2c);
            this.neuPictureBox1.Name = "neuPictureBox1";
            this.neuPictureBox1.Size = new Size(130, 0x30);
            this.neuPictureBox1.Style = StyleType.Fixed3D;
            this.neuPictureBox1.TabIndex = 0x3d;
            this.neuPictureBox1.TabStop = false;
            this.neuLabel8.AutoSize = true;
            this.neuLabel8.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel8.Location = new Point(0x1a6, 0x29);
            this.neuLabel8.Name = "neuLabel8";
            this.neuLabel8.Size = new Size(0x31, 14);
            this.neuLabel8.Style = StyleType.Fixed3D;
            this.neuLabel8.TabIndex = 7;
            this.neuLabel8.Text = "性别：";
            this.neuLabel10.AutoSize = true;
            this.neuLabel10.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel10.Location = new Point(0x156, 0x47);
            this.neuLabel10.Name = "neuLabel10";
            this.neuLabel10.Size = new Size(0x31, 14);
            this.neuLabel10.Style = StyleType.Fixed3D;
            this.neuLabel10.TabIndex = 9;
            this.neuLabel10.Text = "日期：";
            this.neuLabel3.AutoSize = true;
            this.neuLabel3.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel3.Location = new Point(0xe0, 0x6a);
            this.neuLabel3.Name = "neuLabel3";
            this.neuLabel3.Size = new Size(0x31, 14);
            this.neuLabel3.Style = StyleType.Fixed3D;
            this.neuLabel3.TabIndex = 11;
            this.neuLabel3.Text = "医生：";
            this.neuPanel1.BackColor = Color.White;
            this.neuPanel1.Controls.Add(this.neuPanel4);
            this.neuPanel1.Dock = DockStyle.Fill;
            this.neuPanel1.Location = new Point(0, 0x8b);
            this.neuPanel1.Name = "neuPanel1";
            this.neuPanel1.Size = new Size(0x2cc, 0x1f5);
            this.neuPanel1.Style = StyleType.Fixed3D;
            this.neuPanel1.TabIndex = 3;
            this.neuPanel4.Controls.Add(this.neuSpread1);
            this.neuPanel4.Location = new Point(0x51, 2);
            this.neuPanel4.Name = "neuPanel4";
            this.neuPanel4.Size = new Size(540, 0x182);
            this.neuPanel4.Style = StyleType.Fixed3D;
            this.neuPanel4.TabIndex = 3;
            this.neuSpread1.About = "3.0.2004.2005";
            this.neuSpread1.AccessibleDescription = "neuSpread1, Sheet1, Row 0, Column 0, ";
            this.neuSpread1.BackColor = Color.White;
      //      this.neuSpread1.BorderStyle = BorderStyle.None;
            this.neuSpread1.Dock = DockStyle.Fill;
            this.neuSpread1.FileName = "";
            this.neuSpread1.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuSpread1.HorizontalScrollBarPolicy = ScrollBarPolicy.AsNeeded;
            this.neuSpread1.IsAutoSaveGridStatus = false;
            this.neuSpread1.IsCanCustomConfigColumn = false;
            this.neuSpread1.Location = new Point(0, 0);
            this.neuSpread1.Name = "neuSpread1";
//            this.neuSpread1.RightToLeft = RightToLeft.No;
            this.neuSpread1.Sheets.AddRange(new SheetView[] { this.neuSpread1_Sheet1 });
            this.neuSpread1.Size = new Size(540, 0x182);
            this.neuSpread1.Style = StyleType.Fixed3D;
            this.neuSpread1.TabIndex = 2;
            appearance.BackColor = SystemColors.Info;
            appearance.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            appearance.ForeColor = SystemColors.InfoText;
            this.neuSpread1.TextTipAppearance = appearance;
            this.neuSpread1.VerticalScrollBarPolicy = ScrollBarPolicy.AsNeeded;
            this.neuSpread1_Sheet1.Reset();
            this.neuSpread1_Sheet1.SheetName = "Sheet1";
            this.neuSpread1_Sheet1.ReferenceStyle = ReferenceStyle.R1C1;
            this.neuSpread1_Sheet1.ColumnCount = 7;
            this.neuSpread1_Sheet1.RowCount = 8;
            this.neuSpread1_Sheet1.RowHeader.ColumnCount = 0;
            this.neuSpread1_Sheet1.ActiveSkin = new SheetSkin("CustomSkin3", Color.White, Color.White, Color.Black, Color.White, GridLines.Both, Color.White, Color.Empty, Color.Empty, Color.Empty, Color.Empty, Color.Empty, false, false, false, true, true);
            this.neuSpread1_Sheet1.Cells.Get(0, 0).Border = border;
            this.neuSpread1_Sheet1.Cells.Get(0, 1).Border = border2;
            this.neuSpread1_Sheet1.Cells.Get(0, 2).Border = border3;
            this.neuSpread1_Sheet1.Cells.Get(0, 3).Border = border4;
            this.neuSpread1_Sheet1.Cells.Get(0, 4).Border = border5;
            this.neuSpread1_Sheet1.Cells.Get(0, 5).Border = border6;
            this.neuSpread1_Sheet1.Cells.Get(0, 6).Border = border7;
            this.neuSpread1_Sheet1.Cells.Get(1, 0).Border = border8;
            this.neuSpread1_Sheet1.Cells.Get(1, 1).Border = border9;
            this.neuSpread1_Sheet1.Cells.Get(1, 2).Border = border10;
            this.neuSpread1_Sheet1.Cells.Get(1, 3).Border = border11;
            this.neuSpread1_Sheet1.Cells.Get(1, 4).Border = border12;
            this.neuSpread1_Sheet1.Cells.Get(1, 5).Border = border13;
            this.neuSpread1_Sheet1.Cells.Get(1, 6).Border = border14;
            this.neuSpread1_Sheet1.Cells.Get(2, 0).Border = border15;
            this.neuSpread1_Sheet1.Cells.Get(2, 1).Border = border16;
            this.neuSpread1_Sheet1.Cells.Get(2, 2).Border = border17;
            this.neuSpread1_Sheet1.Cells.Get(2, 3).Border = border18;
            this.neuSpread1_Sheet1.Cells.Get(2, 4).Border = border19;
            this.neuSpread1_Sheet1.Cells.Get(2, 5).Border = border20;
            this.neuSpread1_Sheet1.Cells.Get(2, 6).Border = border21;
            this.neuSpread1_Sheet1.Cells.Get(3, 0).Border = border22;
            this.neuSpread1_Sheet1.Cells.Get(3, 1).Border = border23;
            this.neuSpread1_Sheet1.Cells.Get(3, 2).Border = border24;
            this.neuSpread1_Sheet1.Cells.Get(3, 3).Border = border25;
            this.neuSpread1_Sheet1.Cells.Get(3, 4).Border = border26;
            this.neuSpread1_Sheet1.Cells.Get(3, 5).Border = border27;
            this.neuSpread1_Sheet1.Cells.Get(3, 6).Border = border28;
            this.neuSpread1_Sheet1.Cells.Get(4, 0).Border = border29;
            this.neuSpread1_Sheet1.Cells.Get(4, 1).Border = border30;
            this.neuSpread1_Sheet1.Cells.Get(4, 2).Border = border31;
            this.neuSpread1_Sheet1.Cells.Get(4, 3).Border = border32;
            this.neuSpread1_Sheet1.Cells.Get(4, 4).Border = border33;
            this.neuSpread1_Sheet1.Cells.Get(4, 5).Border = border34;
            this.neuSpread1_Sheet1.Cells.Get(4, 6).Border = border35;
            this.neuSpread1_Sheet1.Cells.Get(5, 0).Border = border36;
            this.neuSpread1_Sheet1.Cells.Get(5, 1).Border = border37;
            this.neuSpread1_Sheet1.Cells.Get(5, 2).Border = border38;
            this.neuSpread1_Sheet1.Cells.Get(5, 3).Border = border39;
            this.neuSpread1_Sheet1.Cells.Get(5, 4).Border = border40;
            this.neuSpread1_Sheet1.Cells.Get(5, 5).Border = border41;
            this.neuSpread1_Sheet1.Cells.Get(5, 6).Border = border42;
            this.neuSpread1_Sheet1.Cells.Get(6, 0).Border = border43;
            this.neuSpread1_Sheet1.Cells.Get(6, 1).Border = border44;
            this.neuSpread1_Sheet1.Cells.Get(6, 2).Border = border45;
            this.neuSpread1_Sheet1.Cells.Get(6, 3).Border = border46;
            this.neuSpread1_Sheet1.Cells.Get(6, 4).Border = border47;
            this.neuSpread1_Sheet1.Cells.Get(6, 5).Border = border48;
            this.neuSpread1_Sheet1.Cells.Get(6, 6).Border = border49;
            this.neuSpread1_Sheet1.Cells.Get(7, 0).Border = border50;
            this.neuSpread1_Sheet1.Cells.Get(7, 1).Border = border51;
            this.neuSpread1_Sheet1.Cells.Get(7, 2).Border = border52;
            this.neuSpread1_Sheet1.Cells.Get(7, 3).Border = border53;
            this.neuSpread1_Sheet1.Cells.Get(7, 4).Border = border54;
            this.neuSpread1_Sheet1.Cells.Get(7, 5).Border = border55;
            this.neuSpread1_Sheet1.Cells.Get(7, 6).Border = border56;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 0).Border = border57;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 0).Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "组别";
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 1).Border = border58;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "药品名称";
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 2).Border = border59;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "剂量";
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 3).Border = border60;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "用法";
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 4).Border = border61;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 4).Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "滴/分";
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 5).Border = border62;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "注射（接瓶）时间";
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 6).Border = border63;
            this.neuSpread1_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "签名";
            this.neuSpread1_Sheet1.ColumnHeader.DefaultStyle.BackColor = Color.White;
            this.neuSpread1_Sheet1.ColumnHeader.DefaultStyle.Parent = "HeaderDefault";
            this.neuSpread1_Sheet1.ColumnHeader.HorizontalGridLine = new GridLine(GridLineType.Flat, Color.Black, Color.Black, Color.Black);
            this.neuSpread1_Sheet1.ColumnHeader.Rows.Get(0).Height = 40f;
            this.neuSpread1_Sheet1.ColumnHeader.VerticalGridLine = new GridLine(GridLineType.None);
            this.neuSpread1_Sheet1.Columns.Get(0).Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuSpread1_Sheet1.Columns.Get(0).Label = "组别";
            this.neuSpread1_Sheet1.Columns.Get(0).Width = 28f;
            this.neuSpread1_Sheet1.Columns.Get(1).Label = "药品名称";
            this.neuSpread1_Sheet1.Columns.Get(1).Width = 209f;
            type.WordWrap = true;
            this.neuSpread1_Sheet1.Columns.Get(2).CellType = type;
            this.neuSpread1_Sheet1.Columns.Get(2).Font = new Font("宋体", 10f);
            this.neuSpread1_Sheet1.Columns.Get(2).Label = "剂量";
            this.neuSpread1_Sheet1.Columns.Get(2).Width = 67f;
            type2.WordWrap = true;
            this.neuSpread1_Sheet1.Columns.Get(3).CellType = type2;
            this.neuSpread1_Sheet1.Columns.Get(3).Font = new Font("宋体", 10f);
            this.neuSpread1_Sheet1.Columns.Get(3).Label = "用法";
            this.neuSpread1_Sheet1.Columns.Get(3).Width = 58f;
            type3.WordWrap = true;
            this.neuSpread1_Sheet1.Columns.Get(4).CellType = type3;
            this.neuSpread1_Sheet1.Columns.Get(4).Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuSpread1_Sheet1.Columns.Get(4).Label = "滴/分";
            this.neuSpread1_Sheet1.Columns.Get(4).Width = 45f;
            this.neuSpread1_Sheet1.Columns.Get(5).CellType = type4;
            this.neuSpread1_Sheet1.Columns.Get(5).Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuSpread1_Sheet1.Columns.Get(5).Label = "注射（接瓶）时间";
            this.neuSpread1_Sheet1.Columns.Get(5).Width = 76f;
            this.neuSpread1_Sheet1.Columns.Get(6).Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuSpread1_Sheet1.Columns.Get(6).Label = "签名";
            this.neuSpread1_Sheet1.Columns.Get(6).Width = 67f;
            this.neuSpread1_Sheet1.DefaultStyle.BackColor = Color.White;
            this.neuSpread1_Sheet1.DefaultStyle.ForeColor = Color.Black;
            this.neuSpread1_Sheet1.HorizontalGridLine = new GridLine(GridLineType.Flat, Color.Black, Color.Black, Color.Black);
            this.neuSpread1_Sheet1.OperationMode = OperationMode.ExtendedSelect;
            this.neuSpread1_Sheet1.RowHeader.AutoText = HeaderAutoText.Letters;
            this.neuSpread1_Sheet1.RowHeader.Columns.Default.Resizable = true;
            this.neuSpread1_Sheet1.RowHeader.DefaultStyle.BackColor = Color.White;
            this.neuSpread1_Sheet1.RowHeader.DefaultStyle.Parent = "HeaderDefault";
            this.neuSpread1_Sheet1.Rows.Default.Height = 40f;
            this.neuSpread1_Sheet1.SelectionPolicy = SelectionPolicy.MultiRange;
            this.neuSpread1_Sheet1.SelectionUnit = SelectionUnit.Row;
            this.neuSpread1_Sheet1.SheetCornerStyle.BackColor = Color.White;
            this.neuSpread1_Sheet1.SheetCornerStyle.Parent = "CornerDefault";
            this.neuSpread1_Sheet1.StartingColumnNumber = 0;
            this.neuSpread1_Sheet1.StartingRowNumber = 0;
            this.neuSpread1_Sheet1.VerticalGridLine = new GridLine(GridLineType.Flat, Color.Black, SystemColors.ControlLightLight, Color.Black);
            this.neuSpread1_Sheet1.VisualStyles = VisualStyles.Off;
            this.neuSpread1_Sheet1.ReferenceStyle = ReferenceStyle.A1;
            this.panel1.Controls.Add(this.neuLabel5);
            this.panel1.Dock = DockStyle.Bottom;
            this.panel1.Location = new Point(0, 640);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0x2cc, 160);
            this.panel1.TabIndex = 4;
            this.neuLabel5.AutoSize = true;
            this.neuLabel5.Font = new Font("宋体", 12f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel5.Location = new Point(0x65, 0x3a);
            this.neuLabel5.Name = "neuLabel5";
            this.neuLabel5.Size = new Size(480, 0x10);
            this.neuLabel5.Style = StyleType.Fixed3D;
            this.neuLabel5.TabIndex = 0x12;
            this.neuLabel5.Text = "配药人：       核对人：          拔针时间：        拔针人：";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
//            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.White;
            base.Controls.Add(this.neuPanel1);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.neuPanel2);
            base.Name = "ucPrintInjectScoutCard";
            base.Size = new Size(0x2cc, 800);
            base.Load += new EventHandler(this.ucPrintItinerateLarge_Load);
            this.neuPanel2.ResumeLayout(false);
            this.neuPanel2.PerformLayout();
            this.neuPanel3.ResumeLayout(false);
            this.neuPanel3.PerformLayout();
            ((ISupportInitialize)this.neuPictureBox3).EndInit();
            ((ISupportInitialize)this.neuPictureBox2).EndInit();
            ((ISupportInitialize)this.neuPictureBox1).EndInit();
            this.neuPanel1.ResumeLayout(false);
            this.neuPanel4.ResumeLayout(false);
            ((ISupportInitialize)this.neuSpread1).EndInit();
            ((ISupportInitialize)this.neuSpread1_Sheet1).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            base.ResumeLayout(false);
        }


        private NeuLabel lbAge;
        private NeuLabel lblDiag;
        private NeuLabel lblTitle;
        private NeuLabel lbName;
        private NeuLabel lbSex;
        private NeuLabel lbTime;
        private int maxPageNO = 1;
        private NeuLabel neuLabel10;
        private NeuLabel neuLabel12;
        private NeuLabel neuLabel2;
        private NeuLabel neuLabel3;
        private NeuLabel neuLabel4;
        private NeuLabel neuLabel5;
        private NeuLabel neuLabel6;
        private NeuLabel neuLabel8;
        private NeuLabel neuLabel9;
        private NeuLabel neuLbDoct;
        private NeuPanel neuPanel1;
        private NeuPanel neuPanel2;
        private NeuPanel neuPanel3;
        private NeuPanel neuPanel4;
        private NeuPictureBox neuPictureBox1;
        private NeuPictureBox neuPictureBox2;
        private NeuPictureBox neuPictureBox3;
        private NeuSpread neuSpread1;
        private SheetView neuSpread1_Sheet1;
        private NeuLabel nlbPageNo;
        private Panel panel1;

        #endregion
    }
}
