using BarcodeLib;
using FarPoint.Win.Spread;
using FarPoint.Win.Spread.Model;
using Neusoft.FrameWork.WinForms.Classes;
using Neusoft.FrameWork.WinForms.Controls;
using Neusoft.HISFC.BizLogic.Manager;
using Neusoft.HISFC.BizLogic.Nurse;
using Neusoft.HISFC.BizProcess.Interface.Nurse;
using Neusoft.HISFC.Components.Common.Classes;
using Neusoft.HISFC.Models.Nurse;
using Neusoft.SOC.Local.Nurse.Properties;
using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;

namespace Neusoft.SOC.Local.Nurse.ShenZhen
{
    partial class ucRecipePrint
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            TipAppearance appearance = new TipAppearance();
            this.neuLabel10 = new NeuLabel();
            this.pnlRecipe = new NeuPanel();
            this.fpSpread1 = new NeuSpread();
            this.neuSpread1_Sheet1 = new SheetView();
            this.neuLabel3 = new NeuLabel();
            this.panel12 = new Panel();
            this.neuLabel40 = new NeuLabel();
            this.neuLabel87 = new NeuLabel();
            this.neuPanel3 = new NeuPanel();
            this.neuLabel27 = new NeuLabel();
            this.neuLabel63 = new NeuLabel();
            this.panel33 = new Panel();
            this.panel32 = new Panel();
            this.panel21 = new Panel();
            this.panel22 = new Panel();
            this.panel23 = new Panel();
            this.panel24 = new Panel();
            this.panel25 = new Panel();
            this.panel26 = new Panel();
            this.panel27 = new Panel();
            this.panel28 = new Panel();
            this.panel29 = new Panel();
            this.panel30 = new Panel();
            this.neuLabel21 = new NeuLabel();
            this.panel31 = new Panel();
            this.neuLabel22 = new NeuLabel();
            this.neuLabel25 = new NeuLabel();
            this.neuLabel26 = new NeuLabel();
            this.lblCommonDocName = new NeuLabel();
            this.neuLabel11 = new NeuLabel();
            this.neuLabel47 = new NeuLabel();
            this.lbName = new NeuLabel();
            this.neuLabel45 = new NeuLabel();
            this.lbSex = new NeuLabel();
            this.neuLabel43 = new NeuLabel();
            this.lbAge = new NeuLabel();
            this.neuLabel41 = new NeuLabel();
            this.neuLbCardNo = new NeuLabel();
            this.neuLabel49 = new NeuLabel();
            this.lblDept = new NeuLabel();
            this.neuLabel32 = new NeuLabel();
            this.lblSeeDate1 = new NeuLabel();
            this.panel6 = new Panel();
            this.neuLabel31 = new NeuLabel();
            this.lblPact1 = new NeuLabel();
            this.neuLabel4 = new NeuLabel();
            this.panel5 = new Panel();
            this.neuLabel95 = new NeuLabel();
            this.neuLabel94 = new NeuLabel();
            this.lblDiagnose1 = new System.Windows.Forms.RichTextBox();
            this.neuLabel17 = new NeuLabel();
            this.neuLabel16 = new NeuLabel();
            this.neuLabel28 = new NeuLabel();
            this.neuLabel37 = new NeuLabel();
            this.pnlTitle1 = new NeuPanel();
            this.panel2 = new Panel();
            this.neuLabel1 = new NeuLabel();
            this.neuLabel2 = new NeuLabel();
            this.panel3 = new Panel();
            this.neuPictureBox1 = new NeuPictureBox();
            this.pictureBox2 = new PictureBox();
            this.neuPanel1 = new NeuPanel();
            this.neuPictureBox2 = new NeuPictureBox();
            this.pnlRecipe.SuspendLayout();
            ((ISupportInitialize)this.fpSpread1).BeginInit();
            ((ISupportInitialize)this.neuSpread1_Sheet1).BeginInit();
            this.neuPanel3.SuspendLayout();
            this.pnlTitle1.SuspendLayout();
            ((ISupportInitialize)this.neuPictureBox1).BeginInit();
            ((ISupportInitialize)this.pictureBox2).BeginInit();
            this.neuPanel1.SuspendLayout();
            ((ISupportInitialize)this.neuPictureBox2).BeginInit();
            base.SuspendLayout();
            this.neuLabel10.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.neuLabel10.AutoSize = true;
            this.neuLabel10.BackColor = Color.Transparent;
            this.neuLabel10.Font = new Font("Microsoft Sans Serif", 18f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.neuLabel10.Location = new Point(0x4c, 3);
            this.neuLabel10.Name = "neuLabel10";
            this.neuLabel10.Size = new Size(420, 0x1d);
            this.neuLabel10.Style = StyleType.Fixed3D;
            this.neuLabel10.TabIndex = 0x11;
            this.neuLabel10.Text = "香港大学深圳医院 静脉输液（血）单";
            this.neuLabel10.TextAlign = ContentAlignment.MiddleCenter;
            this.pnlRecipe.BackColor = SystemColors.Window;
            this.pnlRecipe.Controls.Add(this.fpSpread1);
            this.pnlRecipe.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.pnlRecipe.Location = new Point(0x8d, 0xca);
            this.pnlRecipe.Name = "pnlRecipe";
            this.pnlRecipe.Size = new Size(500, 0x182);
            this.pnlRecipe.Style = StyleType.Fixed3D;
            this.pnlRecipe.TabIndex = 1;
            this.fpSpread1.About = "3.0.2004.2005";
            this.fpSpread1.AccessibleDescription = "fpSpread1, Sheet1, Row 0, Column 0, ";
            this.fpSpread1.BackColor = Color.White;
  //          this.fpSpread1.BorderStyle = BorderStyle.None;
            this.fpSpread1.Dock = DockStyle.Fill;
            this.fpSpread1.FileName = "";
            this.fpSpread1.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.fpSpread1.HorizontalScrollBarPolicy = ScrollBarPolicy.AsNeeded;
            this.fpSpread1.IsAutoSaveGridStatus = false;
            this.fpSpread1.IsCanCustomConfigColumn = false;
            this.fpSpread1.Location = new Point(0, 0);
            this.fpSpread1.Name = "fpSpread1";
            this.fpSpread1.Sheets.AddRange(new SheetView[] { this.neuSpread1_Sheet1 });
            this.fpSpread1.Size = new Size(500, 0x182);
            this.fpSpread1.Style = StyleType.Fixed3D;
            this.fpSpread1.TabIndex = 1;
            appearance.BackColor = SystemColors.Info;
            appearance.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            appearance.ForeColor = SystemColors.InfoText;
            this.fpSpread1.TextTipAppearance = appearance;
            this.fpSpread1.VerticalScrollBarPolicy = ScrollBarPolicy.AsNeeded;
            this.fpSpread1.CellClick += new CellClickEventHandler(this.fpSpread1_CellClick);
            this.neuSpread1_Sheet1.Reset();
            this.neuSpread1_Sheet1.SheetName = "Sheet1";
            this.neuSpread1_Sheet1.ReferenceStyle = ReferenceStyle.R1C1;
            this.neuSpread1_Sheet1.ColumnCount = 11;
            this.neuSpread1_Sheet1.ColumnHeader.RowCount = 0;
            this.neuSpread1_Sheet1.RowCount = 0x12;
            this.neuSpread1_Sheet1.RowHeader.ColumnCount = 0;
            this.neuSpread1_Sheet1.HorizontalGridLine = new GridLine(GridLineType.Flat, Color.White);
            this.neuSpread1_Sheet1.VerticalGridLine = new GridLine(GridLineType.Flat, Color.White);
            this.neuSpread1_Sheet1.ReferenceStyle = ReferenceStyle.A1;
            this.neuLabel3.AutoSize = true;
            this.neuLabel3.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel3.Location = new Point(0x211, 0x266);
            this.neuLabel3.Name = "neuLabel3";
            this.neuLabel3.Size = new Size(0x2a, 14);
            this.neuLabel3.Style = StyleType.Fixed3D;
            this.neuLabel3.TabIndex = 0x29;
            this.neuLabel3.Text = "医师:";
            this.panel12.BackColor = Color.Black;
            this.panel12.ForeColor = Color.White;
            this.panel12.Location = new Point(0x8f, 0x279);
            this.panel12.Name = "panel12";
            this.panel12.Size = new Size(0x1f2, 1);
            this.panel12.TabIndex = 0x31;
            this.neuLabel40.AutoSize = true;
            this.neuLabel40.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel40.Location = new Point(0x12f, 0x270);
            this.neuLabel40.Name = "neuLabel40";
            this.neuLabel40.Size = new Size(0, 14);
            this.neuLabel40.Style = StyleType.Fixed3D;
            this.neuLabel40.TabIndex = 0x36;
            this.neuLabel87.AutoSize = true;
            this.neuLabel87.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel87.Location = new Point(0x1e9, 0x270);
            this.neuLabel87.Name = "neuLabel87";
            this.neuLabel87.Size = new Size(0, 14);
            this.neuLabel87.Style = StyleType.Fixed3D;
            this.neuLabel87.TabIndex = 0x3a;
            this.neuLabel87.Tag = "";
            this.neuPanel3.Controls.Add(this.neuLabel27);
            this.neuPanel3.Controls.Add(this.neuLabel63);
            this.neuPanel3.Controls.Add(this.panel33);
            this.neuPanel3.Controls.Add(this.panel32);
            this.neuPanel3.Controls.Add(this.panel21);
            this.neuPanel3.Controls.Add(this.panel22);
            this.neuPanel3.Controls.Add(this.panel23);
            this.neuPanel3.Controls.Add(this.panel24);
            this.neuPanel3.Controls.Add(this.panel25);
            this.neuPanel3.Controls.Add(this.panel26);
            this.neuPanel3.Controls.Add(this.panel27);
            this.neuPanel3.Controls.Add(this.panel28);
            this.neuPanel3.Controls.Add(this.panel29);
            this.neuPanel3.Controls.Add(this.panel30);
            this.neuPanel3.Controls.Add(this.neuLabel21);
            this.neuPanel3.Controls.Add(this.panel31);
            this.neuPanel3.Controls.Add(this.neuLabel22);
            this.neuPanel3.Controls.Add(this.neuLabel25);
            this.neuPanel3.Controls.Add(this.neuLabel26);
            this.neuPanel3.Location = new Point(0x8e, 0x2a1);
            this.neuPanel3.Name = "neuPanel3";
            this.neuPanel3.Size = new Size(0x1f1, 0x88);
            this.neuPanel3.Style = StyleType.Fixed3D;
            this.neuPanel3.TabIndex = 0x3e;
            this.neuLabel27.AutoSize = true;
            this.neuLabel27.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel27.Location = new Point(0x11, 0x62);
            this.neuLabel27.Name = "neuLabel27";
            this.neuLabel27.Size = new Size(0x29, 12);
            this.neuLabel27.Style = StyleType.Fixed3D;
            this.neuLabel27.TabIndex = 0x3e;
            this.neuLabel27.Text = "拔针：";
            this.neuLabel63.AutoSize = true;
            this.neuLabel63.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel63.Location = new Point(0x11, 80);
            this.neuLabel63.Name = "neuLabel63";
            this.neuLabel63.Size = new Size(0x29, 12);
            this.neuLabel63.Style = StyleType.Fixed3D;
            this.neuLabel63.TabIndex = 0x3f;
            this.neuLabel63.Text = "接瓶：";
            this.panel33.BackColor = Color.Black;
            this.panel33.ForeColor = Color.White;
            this.panel33.Location = new Point(8, 0x70);
            this.panel33.Name = "panel33";
            this.panel33.Size = new Size(480, 1);
            this.panel33.TabIndex = 0x3e;
            this.panel32.BackColor = Color.Black;
            this.panel32.ForeColor = Color.White;
            this.panel32.Location = new Point(7, 0x4d);
            this.panel32.Name = "panel32";
            this.panel32.Size = new Size(480, 1);
            this.panel32.TabIndex = 0x3e;
            this.panel21.BackColor = Color.Black;
            this.panel21.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel21.ForeColor = Color.White;
            this.panel21.Location = new Point(7, 4);
            this.panel21.Name = "panel21";
            this.panel21.Size = new Size(1, 0x6d);
            this.panel21.TabIndex = 0x3a;
            this.panel22.BackColor = Color.Black;
            this.panel22.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel22.ForeColor = Color.White;
            this.panel22.Location = new Point(0x1e7, 4);
            this.panel22.Name = "panel22";
            this.panel22.Size = new Size(1, 0x6d);
            this.panel22.TabIndex = 0x39;
            this.panel23.BackColor = Color.Black;
            this.panel23.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel23.ForeColor = Color.White;
            this.panel23.Location = new Point(0x185, 4);
            this.panel23.Name = "panel23";
            this.panel23.Size = new Size(1, 0x6d);
            this.panel23.TabIndex = 0x38;
            this.panel24.BackColor = Color.Black;
            this.panel24.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel24.ForeColor = Color.White;
            this.panel24.Location = new Point(0x11f, 4);
            this.panel24.Name = "panel24";
            this.panel24.Size = new Size(1, 0x6d);
            this.panel24.TabIndex = 0x37;
            this.panel25.BackColor = Color.Black;
            this.panel25.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel25.ForeColor = Color.White;
            this.panel25.Location = new Point(0xba, 4);
            this.panel25.Name = "panel25";
            this.panel25.Size = new Size(1, 0x6d);
            this.panel25.TabIndex = 0x36;
            this.panel26.BackColor = Color.Black;
            this.panel26.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel26.ForeColor = Color.White;
            this.panel26.Location = new Point(8, 3);
            this.panel26.Name = "panel26";
            this.panel26.Size = new Size(480, 1);
            this.panel26.TabIndex = 0x35;
            this.panel27.BackColor = Color.Black;
            this.panel27.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel27.ForeColor = Color.White;
            this.panel27.Location = new Point(0x57, 4);
            this.panel27.Name = "panel27";
            this.panel27.Size = new Size(1, 0x6d);
            this.panel27.TabIndex = 0x34;
            this.panel28.BackColor = Color.Black;
            this.panel28.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel28.ForeColor = Color.White;
            this.panel28.Location = new Point(8, 0x15);
            this.panel28.Name = "panel28";
            this.panel28.Size = new Size(480, 1);
            this.panel28.TabIndex = 0x33;
            this.panel29.BackColor = Color.Black;
            this.panel29.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel29.ForeColor = Color.White;
            this.panel29.Location = new Point(8, 0x29);
            this.panel29.Name = "panel29";
            this.panel29.Size = new Size(480, 1);
            this.panel29.TabIndex = 0x33;
            this.panel30.BackColor = Color.Black;
            this.panel30.Font = new Font("宋体", 9.75f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.panel30.ForeColor = Color.White;
            this.panel30.Location = new Point(8, 0x3b);
            this.panel30.Name = "panel30";
            this.panel30.Size = new Size(480, 1);
            this.panel30.TabIndex = 50;
            this.neuLabel21.AutoSize = true;
            this.neuLabel21.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel21.Location = new Point(0x11, 0x19);
            this.neuLabel21.Name = "neuLabel21";
            this.neuLabel21.Size = new Size(0x29, 12);
            this.neuLabel21.Style = StyleType.Fixed3D;
            this.neuLabel21.TabIndex = 0x12;
            this.neuLabel21.Text = "核对：";
            this.panel31.BackColor = Color.Black;
            this.panel31.ForeColor = Color.White;
            this.panel31.Location = new Point(8, 0x5f);
            this.panel31.Name = "panel31";
            this.panel31.Size = new Size(480, 1);
            this.panel31.TabIndex = 40;
            this.neuLabel22.AutoSize = true;
            this.neuLabel22.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel22.Location = new Point(0x11, 0x2c);
            this.neuLabel22.Name = "neuLabel22";
            this.neuLabel22.Size = new Size(0x29, 12);
            this.neuLabel22.Style = StyleType.Fixed3D;
            this.neuLabel22.TabIndex = 13;
            this.neuLabel22.Text = "配药：";
            this.neuLabel25.AutoSize = true;
            this.neuLabel25.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel25.Location = new Point(0x11, 5);
            this.neuLabel25.Name = "neuLabel25";
            this.neuLabel25.Size = new Size(0x29, 12);
            this.neuLabel25.Style = StyleType.Fixed3D;
            this.neuLabel25.TabIndex = 8;
            this.neuLabel25.Text = "日期：";
            this.neuLabel26.AutoSize = true;
            this.neuLabel26.Font = new Font("宋体", 9f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel26.Location = new Point(0x11, 0x3e);
            this.neuLabel26.Name = "neuLabel26";
            this.neuLabel26.Size = new Size(0x29, 12);
            this.neuLabel26.Style = StyleType.Fixed3D;
            this.neuLabel26.TabIndex = 7;
            this.neuLabel26.Text = "注射：";
            this.lblCommonDocName.AutoSize = true;
            this.lblCommonDocName.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lblCommonDocName.Location = new Point(0x241, 0x266);
            this.lblCommonDocName.Name = "lblCommonDocName";
            this.lblCommonDocName.Size = new Size(0x23, 14);
            this.lblCommonDocName.Style = StyleType.Fixed3D;
            this.lblCommonDocName.TabIndex = 0x2a;
            this.lblCommonDocName.Text = "医师";
            this.neuLabel11.AutoSize = true;
            this.neuLabel11.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel11.Location = new Point(0x94, 0x291);
            this.neuLabel11.Name = "neuLabel11";
            this.neuLabel11.Size = new Size(0x19d, 14);
            this.neuLabel11.Style = StyleType.Fixed3D;
            this.neuLabel11.TabIndex = 0x2e;
            this.neuLabel11.Text = "审核药师：            调剂药师/士：        核对/发药药师：";
            this.neuLabel47.AutoSize = true;
            this.neuLabel47.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel47.Location = new Point(4, 0x23);
            this.neuLabel47.Name = "neuLabel47";
            this.neuLabel47.Size = new Size(0x2a, 14);
            this.neuLabel47.Style = StyleType.Fixed3D;
            this.neuLabel47.TabIndex = 7;
            this.neuLabel47.Text = "姓名:";
            this.lbName.AutoSize = true;
            this.lbName.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbName.Location = new Point(0x29, 0x23);
            this.lbName.Name = "lbName";
            this.lbName.Size = new Size(0x23, 14);
            this.lbName.Style = StyleType.Fixed3D;
            this.lbName.TabIndex = 8;
            this.lbName.Text = "张三";
            this.neuLabel45.AutoSize = true;
            this.neuLabel45.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel45.Location = new Point(0x7e, 0x23);
            this.neuLabel45.Name = "neuLabel45";
            this.neuLabel45.Size = new Size(0x2a, 14);
            this.neuLabel45.Style = StyleType.Fixed3D;
            this.neuLabel45.TabIndex = 9;
            this.neuLabel45.Text = "性别:";
            this.lbSex.AutoSize = true;
            this.lbSex.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbSex.Location = new Point(0xa4, 0x23);
            this.lbSex.Name = "lbSex";
            this.lbSex.Size = new Size(0x15, 14);
            this.lbSex.Style = StyleType.Fixed3D;
            this.lbSex.TabIndex = 10;
            this.lbSex.Text = "男";
            this.neuLabel43.AutoSize = true;
            this.neuLabel43.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel43.Location = new Point(0xd6, 0x23);
            this.neuLabel43.Name = "neuLabel43";
            this.neuLabel43.Size = new Size(0x2a, 14);
            this.neuLabel43.Style = StyleType.Fixed3D;
            this.neuLabel43.TabIndex = 11;
            this.neuLabel43.Text = "年龄:";
            this.lbAge.AutoSize = true;
            this.lbAge.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lbAge.Location = new Point(0xfb, 0x23);
            this.lbAge.Name = "lbAge";
            this.lbAge.Size = new Size(0x15, 14);
            this.lbAge.Style = StyleType.Fixed3D;
            this.lbAge.TabIndex = 12;
            this.lbAge.Text = "20";
            this.neuLabel41.AutoSize = true;
            this.neuLabel41.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel41.Location = new Point(4, 0x5d);
            this.neuLabel41.Name = "neuLabel41";
            this.neuLabel41.Size = new Size(70, 14);
            this.neuLabel41.Style = StyleType.Fixed3D;
            this.neuLabel41.TabIndex = 13;
            this.neuLabel41.Text = "临床诊断:";
            this.neuLbCardNo.AutoSize = true;
            this.neuLbCardNo.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLbCardNo.Location = new Point(0x1b4, 0x23);
            this.neuLbCardNo.Name = "neuLbCardNo";
            this.neuLbCardNo.Size = new Size(0x38, 14);
            this.neuLbCardNo.Style = StyleType.Fixed3D;
            this.neuLbCardNo.TabIndex = 2;
            this.neuLbCardNo.Text = "0000000";
            this.neuLabel49.AutoSize = true;
            this.neuLabel49.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel49.Location = new Point(380, 0x23);
            this.neuLabel49.Name = "neuLabel49";
            this.neuLabel49.Size = new Size(0x38, 14);
            this.neuLabel49.Style = StyleType.Fixed3D;
            this.neuLabel49.TabIndex = 0x1a;
            this.neuLabel49.Text = "门诊号:";
            this.lblDept.AutoSize = true;
            this.lblDept.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lblDept.Location = new Point(0x14b, 0x23);
            this.lblDept.Name = "lblDept";
            this.lblDept.Size = new Size(0x23, 14);
            this.lblDept.Style = StyleType.Fixed3D;
            this.lblDept.TabIndex = 20;
            this.lblDept.Text = "挂号";
            this.neuLabel32.AutoSize = true;
            this.neuLabel32.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel32.Location = new Point(0x123, 0x23);
            this.neuLabel32.Name = "neuLabel32";
            this.neuLabel32.Size = new Size(0x2a, 14);
            this.neuLabel32.Style = StyleType.Fixed3D;
            this.neuLabel32.TabIndex = 0x12;
            this.neuLabel32.Text = "科别:";
            this.lblSeeDate1.AutoSize = true;
            this.lblSeeDate1.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lblSeeDate1.Location = new Point(0x19f, 0x41);
            this.lblSeeDate1.Name = "lblSeeDate1";
            this.lblSeeDate1.Size = new Size(0x4d, 14);
            this.lblSeeDate1.Style = StyleType.Fixed3D;
            this.lblSeeDate1.TabIndex = 4;
            this.lblSeeDate1.Text = "2007-01-01";
            this.panel6.BackColor = Color.Black;
            this.panel6.ForeColor = Color.White;
            this.panel6.Location = new Point(5, 0x9d);
            this.panel6.Name = "panel6";
            this.panel6.Size = new Size(490, 2);
            this.panel6.TabIndex = 0x34;
            this.neuLabel31.AutoSize = true;
            this.neuLabel31.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel31.Location = new Point(4, 8);
            this.neuLabel31.Name = "neuLabel31";
            this.neuLabel31.Size = new Size(0x31, 14);
            this.neuLabel31.Style = StyleType.Fixed3D;
            this.neuLabel31.TabIndex = 0x13;
            this.neuLabel31.Text = "费别：";
            this.lblPact1.AutoSize = true;
            this.lblPact1.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lblPact1.Location = new Point(40, 8);
            this.lblPact1.Name = "lblPact1";
            this.lblPact1.Size = new Size(0x23, 14);
            this.lblPact1.Style = StyleType.Fixed3D;
            this.lblPact1.TabIndex = 0x15;
            this.lblPact1.Text = "现金";
            this.neuLabel4.AutoSize = true;
            this.neuLabel4.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel4.Location = new Point(0x165, 0x41);
            this.neuLabel4.Name = "neuLabel4";
            this.neuLabel4.Size = new Size(0x31, 14);
            this.neuLabel4.Style = StyleType.Fixed3D;
            this.neuLabel4.TabIndex = 0x33;
            this.neuLabel4.Text = "日期：";
            this.panel5.BackColor = Color.Black;
            this.panel5.ForeColor = Color.White;
            this.panel5.Location = new Point(2, 0x1b);
            this.panel5.Name = "panel5";
            this.panel5.Size = new Size(0x1f0, 2);
            this.panel5.TabIndex = 0x3b;
            this.neuLabel95.AutoSize = true;
            this.neuLabel95.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel95.Location = new Point(0x10c, 8);
            this.neuLabel95.Name = "neuLabel95";
            this.neuLabel95.Size = new Size(0x3f, 14);
            this.neuLabel95.Style = StyleType.Fixed3D;
            this.neuLabel95.TabIndex = 60;
            this.neuLabel95.Text = "处方号：";
            this.neuLabel94.AutoSize = true;
            this.neuLabel94.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel94.Location = new Point(0x13d, 8);
            this.neuLabel94.Name = "neuLabel94";
            this.neuLabel94.Size = new Size(0x38, 14);
            this.neuLabel94.Style = StyleType.Fixed3D;
            this.neuLabel94.TabIndex = 0x3d;
            this.neuLabel94.Text = "0000000";
            this.lblDiagnose1.AcceptsTab = true;
   //         this.lblDiagnose1.BorderStyle = BorderStyle.None;
            this.lblDiagnose1.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.lblDiagnose1.Location = new Point(0x49, 0x56);
            this.lblDiagnose1.Name = "lblDiagnose1";
            this.lblDiagnose1.Size = new Size(260, 0x22);
            this.lblDiagnose1.TabIndex = 0x3e;
            this.lblDiagnose1.Text = "";
            this.neuLabel17.AutoSize = true;
            this.neuLabel17.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel17.Location = new Point(0x77, 8);
            this.neuLabel17.Name = "neuLabel17";
            this.neuLabel17.Size = new Size(0x3f, 14);
            this.neuLabel17.Style = StyleType.Fixed3D;
            this.neuLabel17.TabIndex = 0x3f;
            this.neuLabel17.Text = "医保号：";
            this.neuLabel16.AutoSize = true;
            this.neuLabel16.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel16.Location = new Point(0xa9, 8);
            this.neuLabel16.Name = "neuLabel16";
            this.neuLabel16.Size = new Size(0x38, 14);
            this.neuLabel16.Style = StyleType.Fixed3D;
            this.neuLabel16.TabIndex = 0x40;
            this.neuLabel16.Text = "0000000";
            this.neuLabel28.AutoSize = true;
            this.neuLabel28.Location = new Point(8, 0x43);
            this.neuLabel28.Name = "neuLabel28";
            this.neuLabel28.Size = new Size(0x41, 12);
            this.neuLabel28.Style = StyleType.Fixed3D;
            this.neuLabel28.TabIndex = 0x41;
            this.neuLabel28.Text = "电话号码：";
            this.neuLabel37.AutoSize = true;
            this.neuLabel37.Location = new Point(0xa5, 0x43);
            this.neuLabel37.Name = "neuLabel37";
            this.neuLabel37.Size = new Size(0x35, 12);
            this.neuLabel37.Style = StyleType.Fixed3D;
            this.neuLabel37.TabIndex = 0x42;
            this.neuLabel37.Text = "过敏史：";
            this.pnlTitle1.Controls.Add(this.panel2);
            this.pnlTitle1.Controls.Add(this.neuLabel37);
            this.pnlTitle1.Controls.Add(this.neuLabel28);
            this.pnlTitle1.Controls.Add(this.neuLabel16);
            this.pnlTitle1.Controls.Add(this.neuLabel17);
            this.pnlTitle1.Controls.Add(this.lblDiagnose1);
            this.pnlTitle1.Controls.Add(this.neuLabel94);
            this.pnlTitle1.Controls.Add(this.neuLabel95);
            this.pnlTitle1.Controls.Add(this.panel5);
            this.pnlTitle1.Controls.Add(this.neuLabel4);
            this.pnlTitle1.Controls.Add(this.lblPact1);
            this.pnlTitle1.Controls.Add(this.neuLabel31);
            this.pnlTitle1.Controls.Add(this.panel6);
            this.pnlTitle1.Controls.Add(this.lblSeeDate1);
            this.pnlTitle1.Controls.Add(this.neuLabel32);
            this.pnlTitle1.Controls.Add(this.lblDept);
            this.pnlTitle1.Controls.Add(this.neuLabel49);
            this.pnlTitle1.Controls.Add(this.neuLbCardNo);
            this.pnlTitle1.Controls.Add(this.neuLabel41);
            this.pnlTitle1.Controls.Add(this.lbAge);
            this.pnlTitle1.Controls.Add(this.neuLabel43);
            this.pnlTitle1.Controls.Add(this.lbSex);
            this.pnlTitle1.Controls.Add(this.neuLabel45);
            this.pnlTitle1.Controls.Add(this.lbName);
            this.pnlTitle1.Controls.Add(this.neuLabel47);
            this.pnlTitle1.Location = new Point(0x8d, 0x52);
            this.pnlTitle1.Name = "pnlTitle1";
            this.pnlTitle1.Size = new Size(500, 0x79);
            this.pnlTitle1.Style = StyleType.Fixed3D;
            this.pnlTitle1.TabIndex = 0x2d;
            this.panel2.BackColor = Color.Black;
            this.panel2.ForeColor = Color.White;
            this.panel2.Location = new Point(2, 0x77);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(0x1f0, 2);
            this.panel2.TabIndex = 60;
            this.neuLabel1.AutoSize = true;
            this.neuLabel1.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel1.Location = new Point(0x98, 640);
            this.neuLabel1.Name = "neuLabel1";
            this.neuLabel1.Size = new Size(0x4d, 14);
            this.neuLabel1.Style = StyleType.Fixed3D;
            this.neuLabel1.TabIndex = 0x3f;
            this.neuLabel1.Text = "院内注射：";
            this.neuLabel2.AutoSize = true;
            this.neuLabel2.Font = new Font("宋体", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0x86);
            this.neuLabel2.Location = new Point(0x134, 0x27f);
            this.neuLabel2.Name = "neuLabel2";
            this.neuLabel2.Size = new Size(0x54, 14);
            this.neuLabel2.Style = StyleType.Fixed3D;
            this.neuLabel2.TabIndex = 0x40;
            this.neuLabel2.Text = "输液费用： ";
            this.panel3.BackColor = Color.Black;
            this.panel3.ForeColor = Color.White;
            this.panel3.Location = new Point(0x8f, 0x25f);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(0x1f2, 1);
            this.panel3.TabIndex = 0x41;
            this.neuPictureBox1.ImageLocation = "";
            this.neuPictureBox1.Location = new Point(0x132, 0x1f);
            this.neuPictureBox1.Name = "neuPictureBox1";
            this.neuPictureBox1.Size = new Size(0x72, 0x23);
            this.neuPictureBox1.Style = StyleType.Fixed3D;
            this.neuPictureBox1.TabIndex = 0x42;
            this.neuPictureBox1.TabStop = false;
//            this.pictureBox2.Image = Resources.卫70;
            this.pictureBox2.Location = new Point(11, 2);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new Size(0x47, 0x48);
            this.pictureBox2.TabIndex = 0x43;
            this.pictureBox2.TabStop = false;
            this.neuPanel1.Controls.Add(this.neuPictureBox2);
            this.neuPanel1.Controls.Add(this.pictureBox2);
            this.neuPanel1.Controls.Add(this.neuPictureBox1);
            this.neuPanel1.Controls.Add(this.neuLabel10);
            this.neuPanel1.Location = new Point(0x8d, 0);
            this.neuPanel1.Name = "neuPanel1";
            this.neuPanel1.Size = new Size(500, 0x52);
            this.neuPanel1.Style = StyleType.Fixed3D;
            this.neuPanel1.TabIndex = 0x44;
            this.neuPictureBox2.Location = new Point(0x1ab, 0x1f);
            this.neuPictureBox2.Name = "neuPictureBox2";
            this.neuPictureBox2.Size = new Size(0x43, 0x30);
            this.neuPictureBox2.Style = StyleType.Fixed3D;
            this.neuPictureBox2.TabIndex = 0x44;
            this.neuPictureBox2.TabStop = false;
            this.BackColor = SystemColors.Window;
            base.Controls.Add(this.panel3);
            base.Controls.Add(this.neuLabel2);
            base.Controls.Add(this.neuLabel1);
            base.Controls.Add(this.neuPanel3);
            base.Controls.Add(this.pnlTitle1);
            base.Controls.Add(this.neuLabel87);
            base.Controls.Add(this.neuLabel40);
            base.Controls.Add(this.pnlRecipe);
            base.Controls.Add(this.panel12);
            base.Controls.Add(this.neuLabel11);
            base.Controls.Add(this.lblCommonDocName);
            base.Controls.Add(this.neuLabel3);
            base.Controls.Add(this.neuPanel1);
            base.Name = "ucRecipePrint";
            base.Size = new Size(0x2fa, 0x32c);
            base.Load += new EventHandler(this.ucRecipePrint_Load);
            this.pnlRecipe.ResumeLayout(false);
            ((ISupportInitialize)this.fpSpread1).EndInit();
            ((ISupportInitialize)this.neuSpread1_Sheet1).EndInit();
            this.neuPanel3.ResumeLayout(false);
            this.neuPanel3.PerformLayout();
            this.pnlTitle1.ResumeLayout(false);
            this.pnlTitle1.PerformLayout();
            ((ISupportInitialize)this.neuPictureBox1).EndInit();
            ((ISupportInitialize)this.pictureBox2).EndInit();
            this.neuPanel1.ResumeLayout(false);
            this.neuPanel1.PerformLayout();
            ((ISupportInitialize)this.neuPictureBox2).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private int curPageNO = 1;
        private NeuSpread fpSpread1;
        private Neusoft.HISFC.BizLogic.Nurse.Inject injectMgr = new Neusoft.HISFC.BizLogic.Nurse.Inject();
        private bool isReprint = false;
        private NeuLabel lbAge;
        private NeuLabel lblCommonDocName;
        private NeuLabel lblDept;
        private System.Windows.Forms.RichTextBox lblDiagnose1;
        private NeuLabel lblPact1;
        private NeuLabel lblSeeDate1;
        private NeuLabel lbName;
        private NeuLabel lbSex;
        private int maxPageNO = 1;
        private NeuLabel neuLabel1;
        private NeuLabel neuLabel10;
        private NeuLabel neuLabel11;
        private NeuLabel neuLabel16;
        private NeuLabel neuLabel17;
        private NeuLabel neuLabel2;
        private NeuLabel neuLabel21;
        private NeuLabel neuLabel22;
        private NeuLabel neuLabel25;
        private NeuLabel neuLabel26;
        private NeuLabel neuLabel27;
        private NeuLabel neuLabel28;
        private NeuLabel neuLabel3;
        private NeuLabel neuLabel31;
        private NeuLabel neuLabel32;
        private NeuLabel neuLabel37;
        private NeuLabel neuLabel4;
        private NeuLabel neuLabel40;
        private NeuLabel neuLabel41;
        private NeuLabel neuLabel43;
        private NeuLabel neuLabel45;
        private NeuLabel neuLabel47;
        private NeuLabel neuLabel49;
        private NeuLabel neuLabel63;
        private NeuLabel neuLabel87;
        private NeuLabel neuLabel94;
        private NeuLabel neuLabel95;
        private NeuLabel neuLbCardNo;
        private NeuPanel neuPanel1;
        private NeuPanel neuPanel3;
        private NeuPictureBox neuPictureBox1;
        private NeuPictureBox neuPictureBox2;
        private SheetView neuSpread1_Sheet1;
        private Panel panel12;
        private Panel panel2;
        private Panel panel21;
        private Panel panel22;
        private Panel panel23;
        private Panel panel24;
        private Panel panel25;
        private Panel panel26;
        private Panel panel27;
        private Panel panel28;
        private Panel panel29;
        private Panel panel3;
        private Panel panel30;
        private Panel panel31;
        private Panel panel32;
        private Panel panel33;
        private Panel panel5;
        private Panel panel6;
        private PictureBox pictureBox2;
        private NeuPanel pnlRecipe;
        private NeuPanel pnlTitle1;

        #endregion
    }
}
