//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9148
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

//{09B08BE4-9AC8-4094-9D25-0CA5B8C615AB}
namespace FS.HISFC.BizProcess.Integrate {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("HIS", "2.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IbornMobileServiceSoap", Namespace="http://tempuri.org/")]
    public partial class IbornMobileService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IbornMobileService() {
            this.Url = "http://192.168.34.9:8020/IbornMobileService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryBindPatient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryBindPatient(string req) {
            object[] results = this.Invoke("queryBindPatient", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryBindPatient(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryBindPatient", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryBindPatient(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryHISPatientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryHISPatientInfo(string req) {
            object[] results = this.Invoke("queryHISPatientInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryHISPatientInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryHISPatientInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryHISPatientInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPatientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPatientInfo(string req) {
            object[] results = this.Invoke("getPatientInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPatientInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPatientInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPatientInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bindHISPatientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string bindHISPatientInfo(string req) {
            object[] results = this.Invoke("bindHISPatientInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginbindHISPatientInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("bindHISPatientInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndbindHISPatientInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateHISPatientFamily", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updateHISPatientFamily(string req) {
            object[] results = this.Invoke("updateHISPatientFamily", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateHISPatientFamily(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateHISPatientFamily", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndupdateHISPatientFamily(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRealTimeRealIncome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getRealTimeRealIncome(string req) {
            object[] results = this.Invoke("getRealTimeRealIncome", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRealTimeRealIncome(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRealTimeRealIncome", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRealTimeRealIncome(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryPatientCostRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryPatientCostRecord(string req) {
            object[] results = this.Invoke("queryPatientCostRecord", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryPatientCostRecord(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryPatientCostRecord", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryPatientCostRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryPatientCostDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryPatientCostDetail(string req) {
            object[] results = this.Invoke("queryPatientCostDetail", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginqueryPatientCostDetail(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("queryPatientCostDetail", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndqueryPatientCostDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvoiceInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvoiceInfo(string req) {
            object[] results = this.Invoke("getInvoiceInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInvoiceInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInvoiceInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInvoiceInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvoiceDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInvoiceDetail(string req) {
            object[] results = this.Invoke("getInvoiceDetail", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInvoiceDetail(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInvoiceDetail", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInvoiceDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCrmLabel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCrmLabel(string req) {
            object[] results = this.Invoke("getCrmLabel", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCrmLabel(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCrmLabel", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCrmLabel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/postCrmLabel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postCrmLabel(string req) {
            object[] results = this.Invoke("postCrmLabel", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpostCrmLabel(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("postCrmLabel", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndpostCrmLabel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterForCRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegisterForCRM(string req) {
            object[] results = this.Invoke("RegisterForCRM", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterForCRM(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterForCRM", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndRegisterForCRM(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelRegisterForCRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelRegisterForCRM(string req) {
            object[] results = this.Invoke("CancelRegisterForCRM", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelRegisterForCRM(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelRegisterForCRM", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCancelRegisterForCRM(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WriteBackToRegiser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WriteBackToRegiser(string req) {
            object[] results = this.Invoke("WriteBackToRegiser", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWriteBackToRegiser(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WriteBackToRegiser", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndWriteBackToRegiser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUmiaoInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUmiaoInfo(string admissionNumber) {
            object[] results = this.Invoke("GetUmiaoInfo", new object[] {
                        admissionNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUmiaoInfo(string admissionNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUmiaoInfo", new object[] {
                        admissionNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetUmiaoInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCouponAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCouponAccount(string req) {
            object[] results = this.Invoke("GetCouponAccount", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCouponAccount(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCouponAccount", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetCouponAccount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OperateCoupon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OperateCoupon(string req) {
            object[] results = this.Invoke("OperateCoupon", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOperateCoupon(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OperateCoupon", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOperateCoupon(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CostCoupon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CostCoupon(string req) {
            object[] results = this.Invoke("CostCoupon", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCostCoupon(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CostCoupon", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCostCoupon(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/crmRelay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string crmRelay(string req) {
            object[] results = this.Invoke("crmRelay", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincrmRelay(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("crmRelay", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcrmRelay(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MedicalReminder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MedicalReminder(string req) {
            object[] results = this.Invoke("MedicalReminder", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMedicalReminder(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MedicalReminder", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndMedicalReminder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueuingReminder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueuingReminder(string req) {
            object[] results = this.Invoke("QueuingReminder", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQueuingReminder(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("QueuingReminder", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndQueuingReminder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeAssignState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangeAssignState(string req) {
            object[] results = this.Invoke("ChangeAssignState", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangeAssignState(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangeAssignState", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndChangeAssignState(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelAssignSee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelAssignSee(string req) {
            object[] results = this.Invoke("CancelAssignSee", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelAssignSee(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelAssignSee", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCancelAssignSee(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssignSee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AssignSee(string req) {
            object[] results = this.Invoke("AssignSee", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAssignSee(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AssignSee", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAssignSee(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssignPass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AssignPass(string req) {
            object[] results = this.Invoke("AssignPass", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAssignPass(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AssignPass", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAssignPass(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InterfaceTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InterfaceTest() {
            object[] results = this.Invoke("InterfaceTest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInterfaceTest(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InterfaceTest", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInterfaceTest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDoctorInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDoctorInfo(string req) {
            object[] results = this.Invoke("getDoctorInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDoctorInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDoctorInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetDoctorInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getOutpatientInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getOutpatientInfo(string req) {
            object[] results = this.Invoke("getOutpatientInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetOutpatientInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOutpatientInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetOutpatientInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDeptInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDeptInfo(string req) {
            object[] results = this.Invoke("getDeptInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDeptInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDeptInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetDeptInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getScheduleInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getScheduleInfo(string req) {
            object[] results = this.Invoke("getScheduleInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetScheduleInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getScheduleInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetScheduleInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getScheduleInfoToday", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getScheduleInfoToday(string req) {
            object[] results = this.Invoke("getScheduleInfoToday", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetScheduleInfoToday(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getScheduleInfoToday", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetScheduleInfoToday(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLisReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLisReport(string req) {
            object[] results = this.Invoke("getLisReport", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLisReport(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLisReport", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetLisReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLisReportItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getLisReportItem(string req) {
            object[] results = this.Invoke("getLisReportItem", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLisReportItem(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLisReportItem", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetLisReportItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPacsReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPacsReport(string req) {
            object[] results = this.Invoke("getPacsReport", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPacsReport(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPacsReport", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPacsReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPacsReportItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPacsReportItem(string req) {
            object[] results = this.Invoke("getPacsReportItem", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPacsReportItem(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPacsReportItem", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPacsReportItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPesList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPesList(string req) {
            object[] results = this.Invoke("getPesList", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPesList(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPesList", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPesList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRegisterInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getRegisterInfo(string req) {
            object[] results = this.Invoke("getRegisterInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRegisterInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRegisterInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRegisterInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTimeRegInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTimeRegInfo(string req) {
            object[] results = this.Invoke("getTimeRegInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTimeRegInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTimeRegInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetTimeRegInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPeriodInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPeriodInfo(string req) {
            object[] results = this.Invoke("getPeriodInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPeriodInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPeriodInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPeriodInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string addOrder(string req) {
            object[] results = this.Invoke("addOrder", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddOrder(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addOrder", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndaddOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string payOrder(string req) {
            object[] results = this.Invoke("payOrder", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpayOrder(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("payOrder", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndpayOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancelOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cancelOrder(string req) {
            object[] results = this.Invoke("cancelOrder", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelOrder(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelOrder", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcancelOrder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>//{67CE2526-5E7F-4c92-911F-56CA0077679A}
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FamilyOldestPackageDatePoint", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FamilyOldestPackageDatePoint(string req)
        {
            object[] results = this.Invoke("FamilyOldestPackageDatePoint", new object[] {
                        req});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginFamilyOldestPackageDatePoint(string req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("FamilyOldestPackageDatePoint", new object[] {
                        req}, callback, asyncState);
        }

        /// <remarks/>
        public string EndFamilyOldestPackageDatePoint(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDeptInfoToday", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getDeptInfoToday(string req) {
            object[] results = this.Invoke("getDeptInfoToday", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDeptInfoToday(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDeptInfoToday", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetDeptInfoToday(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/lockReg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string lockReg(string req) {
            object[] results = this.Invoke("lockReg", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlockReg(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("lockReg", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndlockReg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/unlockReg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string unlockReg(string req) {
            object[] results = this.Invoke("unlockReg", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginunlockReg(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("unlockReg", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndunlockReg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payRegister", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string payRegister(string req) {
            object[] results = this.Invoke("payRegister", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpayRegister(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("payRegister", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndpayRegister(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPayInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPayInfo(string req) {
            object[] results = this.Invoke("getPayInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPayInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPayInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPayInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLisFuYouReportPatientList", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLisFuYouReportPatientList(string req)
        {
            object[] results = this.Invoke("GetLisFuYouReportPatientList", new object[] {
                        req});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetLisFuYouReportPatientList(string req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetLisFuYouReportPatientList", new object[] {
                        req}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetLisFuYouReportPatientList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLisFuYouReportDetail", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLisFuYouReportDetail(string req)
        {
            object[] results = this.Invoke("GetLisFuYouReportDetail", new object[] {
                        req});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetLisFuYouReportDetail(string req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetLisFuYouReportDetail", new object[] {
                        req}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetLisFuYouReportDetail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPaybillfee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPaybillfee(string req) {
            object[] results = this.Invoke("getPaybillfee", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPaybillfee(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPaybillfee", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPaybillfee(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string pay(string req) {
            object[] results = this.Invoke("pay", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginpay(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("pay", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endpay(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCompletedPayInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCompletedPayInfo(string req) {
            object[] results = this.Invoke("getCompletedPayInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCompletedPayInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCompletedPayInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCompletedPayInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCompletedPayDetailInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCompletedPayDetailInfo(string req) {
            object[] results = this.Invoke("getCompletedPayDetailInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCompletedPayDetailInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCompletedPayDetailInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCompletedPayDetailInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPrescriptionInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPrescriptionInfo(string req) {
            object[] results = this.Invoke("getPrescriptionInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPrescriptionInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPrescriptionInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPrescriptionInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPrescriptionDetailInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPrescriptionDetailInfo(string req) {
            object[] results = this.Invoke("getPrescriptionDetailInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPrescriptionDetailInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPrescriptionDetailInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPrescriptionDetailInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createNewPatient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string createNewPatient(string req) {
            object[] results = this.Invoke("createNewPatient", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewPatient(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewPatient", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcreateNewPatient(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/binding", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string binding(string req) {
            object[] results = this.Invoke("binding", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginbinding(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("binding", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endbinding(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/unBinding", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string unBinding(string req) {
            object[] results = this.Invoke("unBinding", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginunBinding(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("unBinding", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndunBinding(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCardInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCardInfo(string req) {
            object[] results = this.Invoke("getCardInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCardInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCardInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCardInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/payAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string payAccount(string req) {
            object[] results = this.Invoke("payAccount", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpayAccount(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("payAccount", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndpayAccount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/postInpatientCrm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postInpatientCrm(string req) {
            object[] results = this.Invoke("postInpatientCrm", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpostInpatientCrm(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("postInpatientCrm", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndpostInpatientCrm(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAccountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAccountInfo(string req) {
            object[] results = this.Invoke("getAccountInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAccountInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAccountInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAccountInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAccountDetailInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getAccountDetailInfo(string req) {
            object[] results = this.Invoke("getAccountDetailInfo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAccountDetailInfo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAccountDetailInfo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAccountDetailInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackageExeceteInCrm", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PackageExeceteInCrm(string req)
        {
            object[] results = this.Invoke("PackageExeceteInCrm", new object[] {
                        req});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginPackageExeceteInCrm(string req, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("PackageExeceteInCrm", new object[] {
                        req}, callback, asyncState);
        }

        /// <remarks/>
        public string EndPackageExeceteInCrm(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPatientPhoneByCardNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getPatientPhoneByCardNo(string req) {
            object[] results = this.Invoke("getPatientPhoneByCardNo", new object[] {
                        req});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPatientPhoneByCardNo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPatientPhoneByCardNo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndgetPatientPhoneByCardNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPatientCouponInfoByCardNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPatientCouponInfoByCardNo(string req) {
            object[] results = this.Invoke("getPatientCouponInfoByCardNo", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPatientCouponInfoByCardNo(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPatientCouponInfoByCardNo", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPatientCouponInfoByCardNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/couponCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode couponCost(string req) {
            object[] results = this.Invoke("couponCost", new object[] {
                        req});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincouponCost(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("couponCost", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndcouponCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTreatment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getTreatment(string req) {
            object[] results = this.Invoke("getTreatment", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetTreatment(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTreatment", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetTreatment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getClinicTreatment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getClinicTreatment(string req) {
            object[] results = this.Invoke("getClinicTreatment", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetClinicTreatment(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getClinicTreatment", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetClinicTreatment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInHosTreatment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInHosTreatment(string req) {
            object[] results = this.Invoke("getInHosTreatment", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInHosTreatment(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInHosTreatment", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInHosTreatment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCostList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCostList(string req) {
            object[] results = this.Invoke("getCostList", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCostList(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCostList", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCostList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRegCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getRegCost(string req) {
            object[] results = this.Invoke("getRegCost", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRegCost(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRegCost", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRegCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getClinicCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getClinicCost(string req) {
            object[] results = this.Invoke("getClinicCost", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetClinicCost(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getClinicCost", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetClinicCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInHosCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInHosCost(string req) {
            object[] results = this.Invoke("getInHosCost", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInHosCost(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInHosCost", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInHosCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPackageCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPackageCost(string req) {
            object[] results = this.Invoke("getPackageCost", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPackageCost(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPackageCost", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPackageCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPackageScore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPackageScore(string req) {
            object[] results = this.Invoke("getPackageScore", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPackageScore(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPackageScore", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPackageScore(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRechargeCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getRechargeCost(string req) {
            object[] results = this.Invoke("getRechargeCost", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRechargeCost(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRechargeCost", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRechargeCost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPackageDetial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPackageDetial(string req) {
            object[] results = this.Invoke("getPackageDetial", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPackageDetial(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPackageDetial", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPackageDetial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInhosPatientByDoctor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInhosPatientByDoctor(string req) {
            object[] results = this.Invoke("getInhosPatientByDoctor", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInhosPatientByDoctor(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInhosPatientByDoctor", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInhosPatientByDoctor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInhosPatient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInhosPatient(string req) {
            object[] results = this.Invoke("getInhosPatient", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInhosPatient(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInhosPatient", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInhosPatient(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInhosPatientNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getInhosPatientNew(string req) {
            object[] results = this.Invoke("getInhosPatientNew", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetInhosPatientNew(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getInhosPatientNew", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetInhosPatientNew(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getHosIncome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getHosIncome(string req) {
            object[] results = this.Invoke("getHosIncome", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetHosIncome(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHosIncome", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetHosIncome(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getBNum() {
            object[] results = this.Invoke("getBNum", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBNum(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBNum", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetBNum(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        //{1093FFDD-31BD-45c1-9810-3D8AD28BFE89}
        //updatePatientInfoByExceptedTime
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updatePatientInfoByExceptedTime", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string updatePatientInfoByExceptedTime()
        {
            object[] results = this.Invoke("updatePatientInfoByExceptedTime", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginupdatePatientInfoByExceptedTime(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("updatePatientInfoByExceptedTime", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndupdatePatientInfoByExceptedTime(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        //HanTianInvoice

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HanTianInvoice", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HanTianInvoice()
        {
            object[] results = this.Invoke("HanTianInvoice", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHanTianInvoice(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HanTianInvoice", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndHanTianInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }


        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPatientInfoByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPatientInfoByName(string req) {
            object[] results = this.Invoke("getPatientInfoByName", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPatientInfoByName(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPatientInfoByName", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPatientInfoByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCRMWechatApi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCRMWechatApi(string req) {
            object[] results = this.Invoke("getCRMWechatApi", new object[] {
                        req});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCRMWechatApi(string req, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCRMWechatApi", new object[] {
                        req}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCRMWechatApi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
