//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.SOC.Local.Order.LISService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.elims.com.cn/", ConfigurationName="LISService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elims.com.cn/LoadContainerDict", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet LoadContainerDict();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elims.com.cn/CalculateContainer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet CalculateContainer(int aply_itm_type, System.Data.DataTable dt_aply_itms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elims.com.cn/SearchContainerListForHis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet SearchContainerListForHis(int ptnt_no_type, string ptnt_no, string sqnc_no, int state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.elims.com.cn/CallbackContainerPayState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool CallbackContainerPayState(int smpl_flow_id, int state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : FS.SOC.Local.Order.LISService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<FS.SOC.Local.Order.LISService.ServiceSoap>, FS.SOC.Local.Order.LISService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LoadContainerDict() {
            return base.Channel.LoadContainerDict();
        }
        
        public System.Data.DataSet CalculateContainer(int aply_itm_type, System.Data.DataTable dt_aply_itms) {
            return base.Channel.CalculateContainer(aply_itm_type, dt_aply_itms);
        }
        
        public System.Data.DataSet SearchContainerListForHis(int ptnt_no_type, string ptnt_no, string sqnc_no, int state) {
            return base.Channel.SearchContainerListForHis(ptnt_no_type, ptnt_no, sqnc_no, state);
        }
        
        public bool CallbackContainerPayState(int smpl_flow_id, int state) {
            return base.Channel.CallbackContainerPayState(smpl_flow_id, state);
        }
    }
}
