//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.GZSI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.GZSI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 就医地行政区划代码 的本地化字符串。
        /// </summary>
        internal static string aaa027 {
            get {
                return ResourceManager.GetString("aaa027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基金款项代码 的本地化字符串。
        /// </summary>
        internal static string aaa157 {
            get {
                return ResourceManager.GetString("aaa157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位编码 的本地化字符串。
        /// </summary>
        internal static string aab001 {
            get {
                return ResourceManager.GetString("aab001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位类型 的本地化字符串。
        /// </summary>
        internal static string aab019 {
            get {
                return ResourceManager.GetString("aab019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人编号 的本地化字符串。
        /// </summary>
        internal static string aac001 {
            get {
                return ResourceManager.GetString("aac001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社会保障号码 的本地化字符串。
        /// </summary>
        internal static string aac002 {
            get {
                return ResourceManager.GetString("aac002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string aac003 {
            get {
                return ResourceManager.GetString("aac003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string aac004 {
            get {
                return ResourceManager.GetString("aac004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期 的本地化字符串。
        /// </summary>
        internal static string aac006 {
            get {
                return ResourceManager.GetString("aac006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用工形式 的本地化字符串。
        /// </summary>
        internal static string aac013 {
            get {
                return ResourceManager.GetString("aac013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基金名称 的本地化字符串。
        /// </summary>
        internal static string aad006 {
            get {
                return ResourceManager.GetString("aad006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        internal static string aae005 {
            get {
                return ResourceManager.GetString("aae005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请生效时间 的本地化字符串。
        /// </summary>
        internal static string aae030 {
            get {
                return ResourceManager.GetString("aae030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请到期时间 的本地化字符串。
        /// </summary>
        internal static string aae031 {
            get {
                return ResourceManager.GetString("aae031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 险种类型 的本地化字符串。
        /// </summary>
        internal static string aae140 {
            get {
                return ResourceManager.GetString("aae140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门慢申请序列号 的本地化字符串。
        /// </summary>
        internal static string aaz267 {
            get {
                return ResourceManager.GetString("aaz267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受单科室编码 的本地化字符串。
        /// </summary>
        internal static string acordDeptCodg {
            get {
                return ResourceManager.GetString("acordDeptCodg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受单科室名称 的本地化字符串。
        /// </summary>
        internal static string acordDeptName {
            get {
                return ResourceManager.GetString("acordDeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受单医生编码 的本地化字符串。
        /// </summary>
        internal static string acordDrCode {
            get {
                return ResourceManager.GetString("acordDrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受单医生姓名 的本地化字符串。
        /// </summary>
        internal static string acordDrName {
            get {
                return ResourceManager.GetString("acordDrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院床位 的本地化字符串。
        /// </summary>
        internal static string admBed {
            get {
                return ResourceManager.GetString("admBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院病情 的本地化字符串。
        /// </summary>
        internal static string admCond {
            get {
                return ResourceManager.GetString("admCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院科室编 码 的本地化字符串。
        /// </summary>
        internal static string admDeptCodg {
            get {
                return ResourceManager.GetString("admDeptCodg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院科室名 称 的本地化字符串。
        /// </summary>
        internal static string admDeptName {
            get {
                return ResourceManager.GetString("admDeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院诊断描 述 的本地化字符串。
        /// </summary>
        internal static string admDiagDscr {
            get {
                return ResourceManager.GetString("admDiagDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用统计类别 的本地化字符串。
        /// </summary>
        internal static string aka063 {
            get {
                return ResourceManager.GetString("aka063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构等级 的本地化字符串。
        /// </summary>
        internal static string aka101 {
            get {
                return ResourceManager.GetString("aka101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务类型 的本地化字符串。
        /// </summary>
        internal static string aka130 {
            get {
                return ResourceManager.GetString("aka130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构编码 的本地化字符串。
        /// </summary>
        internal static string akb020 {
            get {
                return ResourceManager.GetString("akb020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构名称 的本地化字符串。
        /// </summary>
        internal static string akb021 {
            get {
                return ResourceManager.GetString("akb021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疾病编码 的本地化字符串。
        /// </summary>
        internal static string akc193 {
            get {
                return ResourceManager.GetString("akc193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算时间 的本地化字符串。
        /// </summary>
        internal static string akc194 {
            get {
                return ResourceManager.GetString("akc194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院诊断 的本地化字符串。
        /// </summary>
        internal static string akc196 {
            get {
                return ResourceManager.GetString("akc196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 床位 的本地化字符串。
        /// </summary>
        internal static string ake020 {
            get {
                return ResourceManager.GetString("ake020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 科室代码 的本地化字符串。
        /// </summary>
        internal static string akf001 {
            get {
                return ResourceManager.GetString("akf001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区编码 的本地化字符串。
        /// </summary>
        internal static string baa027 {
            get {
                return ResourceManager.GetString("baa027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行政职务级别 的本地化字符串。
        /// </summary>
        internal static string bac001 {
            get {
                return ResourceManager.GetString("bac001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开单科室编码 的本地化字符串。
        /// </summary>
        internal static string bilgDeptCodg {
            get {
                return ResourceManager.GetString("bilgDeptCodg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开单科室名称 的本地化字符串。
        /// </summary>
        internal static string bilgDeptName {
            get {
                return ResourceManager.GetString("bilgDeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开单医生编码 的本地化字符串。
        /// </summary>
        internal static string bilgDrCode {
            get {
                return ResourceManager.GetString("bilgDrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划生育手术或生育日期 的本地化字符串。
        /// </summary>
        internal static string birctrIMatnDate {
            get {
                return ResourceManager.GetString("birctrIMatnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划生育手 术类别 的本地化字符串。
        /// </summary>
        internal static string birctrIType {
            get {
                return ResourceManager.GetString("birctrIType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务申请类型 的本地化字符串。
        /// </summary>
        internal static string biz_appy_type {
            get {
                return ResourceManager.GetString("biz_appy_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就诊类别 的本地化字符串。
        /// </summary>
        internal static string bka006 {
            get {
                return ResourceManager.GetString("bka006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位名称 的本地化字符串。
        /// </summary>
        internal static string bka008 {
            get {
                return ResourceManager.GetString("bka008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就诊科室名称 的本地化字符串。
        /// </summary>
        internal static string bka020 {
            get {
                return ResourceManager.GetString("bka020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病区编码 的本地化字符串。
        /// </summary>
        internal static string bka021 {
            get {
                return ResourceManager.GetString("bka021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病区名称 的本地化字符串。
        /// </summary>
        internal static string bka022 {
            get {
                return ResourceManager.GetString("bka022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员类别 的本地化字符串。
        /// </summary>
        internal static string bka035 {
            get {
                return ResourceManager.GetString("bka035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就诊类别名称 的本地化字符串。
        /// </summary>
        internal static string bka345 {
            get {
                return ResourceManager.GetString("bka345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付类型 的本地化字符串。
        /// </summary>
        internal static string bka511 {
            get {
                return ResourceManager.GetString("bka511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基金状态标志 的本地化字符串。
        /// </summary>
        internal static string bka888 {
            get {
                return ResourceManager.GetString("bka888", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊人员对象类型 的本地化字符串。
        /// </summary>
        internal static string bka910 {
            get {
                return ResourceManager.GetString("bka910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 救助对象类型 的本地化字符串。
        /// </summary>
        internal static string bka920 {
            get {
                return ResourceManager.GetString("bka920", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊疗代码 的本地化字符串。
        /// </summary>
        internal static string bkb135 {
            get {
                return ResourceManager.GetString("bkb135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构级别 的本地化字符串。
        /// </summary>
        internal static string bke301 {
            get {
                return ResourceManager.GetString("bke301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血型 的本地化字符串。
        /// </summary>
        internal static string bkf001 {
            get {
                return ResourceManager.GetString("bkf001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院方式 的本地化字符串。
        /// </summary>
        internal static string bkf002 {
            get {
                return ResourceManager.GetString("bkf002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入院情况 的本地化字符串。
        /// </summary>
        internal static string bkf003 {
            get {
                return ResourceManager.GetString("bkf003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院转归情况 的本地化字符串。
        /// </summary>
        internal static string bkf004 {
            get {
                return ResourceManager.GetString("bkf004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记账流水号 的本地化字符串。
        /// </summary>
        internal static string bkkpSn {
            get {
                return ResourceManager.GetString("bkkpSn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疾病名称 的本地化字符串。
        /// </summary>
        internal static string bkz101 {
            get {
                return ResourceManager.GetString("bkz101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院诊断名称 的本地化字符串。
        /// </summary>
        internal static string bkz102 {
            get {
                return ResourceManager.GetString("bkz102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诊医师代 码 的本地化字符串。
        /// </summary>
        internal static string chfpdrCode {
            get {
                return ResourceManager.GetString("chfpdrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诊医师姓名 的本地化字符串。
        /// </summary>
        internal static string chfpdrName {
            get {
                return ResourceManager.GetString("chfpdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核通过标 识 的本地化字符串。
        /// </summary>
        internal static string chkPassFlag {
            get {
                return ResourceManager.GetString("chkPassFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人姓名 的本地化字符串。
        /// </summary>
        internal static string conerName {
            get {
                return ResourceManager.GetString("conerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伴有并发症标志 的本地化字符串。
        /// </summary>
        internal static string copFlag {
            get {
                return ResourceManager.GetString("copFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成标志 的本地化字符串。
        /// </summary>
        internal static string cpltflag {
            get {
                return ResourceManager.GetString("cpltflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建机构 的本地化字符串。
        /// </summary>
        internal static string crteOptinsNo {
            get {
                return ResourceManager.GetString("crteOptinsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        internal static string crterId {
            get {
                return ResourceManager.GetString("crterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        internal static string crterld {
            get {
                return ResourceManager.GetString("crterld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人姓名 的本地化字符串。
        /// </summary>
        internal static string crterName {
            get {
                return ResourceManager.GetString("crterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string crteTime {
            get {
                return ResourceManager.GetString("crteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细项目费用总额 的本地化字符串。
        /// </summary>
        internal static string detltemFeeSumamt {
            get {
                return ResourceManager.GetString("detltemFeeSumamt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断代码 的本地化字符串。
        /// </summary>
        internal static string diagCode {
            get {
                return ResourceManager.GetString("diagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断科室 的本地化字符串。
        /// </summary>
        internal static string diagDept {
            get {
                return ResourceManager.GetString("diagDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断医师代码 的本地化字符串。
        /// </summary>
        internal static string diagDrCode {
            get {
                return ResourceManager.GetString("diagDrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断医师姓名 的本地化字符串。
        /// </summary>
        internal static string diagDrName {
            get {
                return ResourceManager.GetString("diagDrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断信息ID 的本地化字符串。
        /// </summary>
        internal static string diagInfoId {
            get {
                return ResourceManager.GetString("diagInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断名称 的本地化字符串。
        /// </summary>
        internal static string diagName {
            get {
                return ResourceManager.GetString("diagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断排序号 的本地化字符串。
        /// </summary>
        internal static string diagSrtNo {
            get {
                return ResourceManager.GetString("diagSrtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断时间 的本地化字符串。
        /// </summary>
        internal static string diagTime {
            get {
                return ResourceManager.GetString("diagTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断类别 的本地化字符串。
        /// </summary>
        internal static string diagType {
            get {
                return ResourceManager.GetString("diagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 死亡日期 的本地化字符串。
        /// </summary>
        internal static string dieDate {
            get {
                return ResourceManager.GetString("dieDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病种名称 的本地化字符串。
        /// </summary>
        internal static string diseName {
            get {
                return ResourceManager.GetString("diseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病种编号 的本地化字符串。
        /// </summary>
        internal static string diseNo {
            get {
                return ResourceManager.GetString("diseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院床位 的本地化字符串。
        /// </summary>
        internal static string dscgBed {
            get {
                return ResourceManager.GetString("dscgBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院科室编 码 的本地化字符串。
        /// </summary>
        internal static string dscgDeptCodg {
            get {
                return ResourceManager.GetString("dscgDeptCodg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院科室名 称 的本地化字符串。
        /// </summary>
        internal static string dscgDeptName {
            get {
                return ResourceManager.GetString("dscgDeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院主诊断 代码 的本地化字符串。
        /// </summary>
        internal static string dscgMaindiagCode {
            get {
                return ResourceManager.GetString("dscgMaindiagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住院主诊断名称 的本地化字符串。
        /// </summary>
        internal static string dscgMaindiagName {
            get {
                return ResourceManager.GetString("dscgMaindiagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出院带药标志 的本地化字符串。
        /// </summary>
        internal static string dscgTkdrugFlag {
            get {
                return ResourceManager.GetString("dscgTkdrugFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离院方式 的本地化字符串。
        /// </summary>
        internal static string dscgWay {
            get {
                return ResourceManager.GetString("dscgWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子票据校 验码 的本地化字符串。
        /// </summary>
        internal static string elecBillChkcode {
            get {
                return ResourceManager.GetString("elecBillChkcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子票据代 码 的本地化字符串。
        /// </summary>
        internal static string elecBillCode {
            get {
                return ResourceManager.GetString("elecBillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子票据号 码 的本地化字符串。
        /// </summary>
        internal static string elecBillnoCode {
            get {
                return ResourceManager.GetString("elecBillnoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外检标志 的本地化字符串。
        /// </summary>
        internal static string etipFlag {
            get {
                return ResourceManager.GetString("etipFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外检医院编码 的本地化字符串。
        /// </summary>
        internal static string etipHospCode {
            get {
                return ResourceManager.GetString("etipHospCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展字段 的本地化字符串。
        /// </summary>
        internal static string expContent {
            get {
                return ResourceManager.GetString("expContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用发生时间 的本地化字符串。
        /// </summary>
        internal static string feeOcurTime {
            get {
                return ResourceManager.GetString("feeOcurTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胎儿数 的本地化字符串。
        /// </summary>
        internal static string fetusCnt {
            get {
                return ResourceManager.GetString("fetusCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主辅标志 的本地化字符串。
        /// </summary>
        internal static string fix_main_scd_flag {
            get {
                return ResourceManager.GetString("fix_main_scd_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定点排序号 的本地化字符串。
        /// </summary>
        internal static string fix_srt_no {
            get {
                return ResourceManager.GetString("fix_srt_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就医点类型 的本地化字符串。
        /// </summary>
        internal static string fix_type {
            get {
                return ResourceManager.GetString("fix_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定点医药机构编号 的本地化字符串。
        /// </summary>
        internal static string fixmedinsCode {
            get {
                return ResourceManager.GetString("fixmedinsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构就诊ID 的本地化字符串。
        /// </summary>
        internal static string fixmedinsMdtrtId {
            get {
                return ResourceManager.GetString("fixmedinsMdtrtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定点医药机构名称 的本地化字符串。
        /// </summary>
        internal static string fixmedinsName {
            get {
                return ResourceManager.GetString("fixmedinsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划生育服 务证号 的本地化字符串。
        /// </summary>
        internal static string fpscNo {
            get {
                return ResourceManager.GetString("fpscNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全自费金额 的本地化字符串。
        /// </summary>
        internal static string fulamtOwnpayAmt {
            get {
                return ResourceManager.GetString("fulamtOwnpayAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孕周数 的本地化字符串。
        /// </summary>
        internal static string gesoVal {
            get {
                return ResourceManager.GetString("gesoVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基层医疗机构标志 的本地化字符串。
        /// </summary>
        internal static string grst_hosp_flag {
            get {
                return ResourceManager.GetString("grst_hosp_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在院状态 的本地化字符串。
        /// </summary>
        internal static string inhospStas {
            get {
                return ResourceManager.GetString("inhospStas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出入院诊断类别 的本地化字符串。
        /// </summary>
        internal static string inoutDiagType {
            get {
                return ResourceManager.GetString("inoutDiagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 符合政策范 围金额 的本地化字符串。
        /// </summary>
        internal static string inscpAmt {
            get {
                return ResourceManager.GetString("inscpAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住院天数 的本地化字符串。
        /// </summary>
        internal static string iptDays {
            get {
                return ResourceManager.GetString("iptDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住院/门诊号 的本地化字符串。
        /// </summary>
        internal static string iptOtpNo {
            get {
                return ResourceManager.GetString("iptOtpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚育标志 的本地化字符串。
        /// </summary>
        internal static string latechbFlag {
            get {
                return ResourceManager.GetString("latechbFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要病情描 述 的本地化字符串。
        /// </summary>
        internal static string mainCondDscr {
            get {
                return ResourceManager.GetString("mainCondDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诊断标志 的本地化字符串。
        /// </summary>
        internal static string maindiagFlag {
            get {
                return ResourceManager.GetString("maindiagFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生育类别 的本地化字符串。
        /// </summary>
        internal static string matnType {
            get {
                return ResourceManager.GetString("matnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医疗收费项目类别 的本地化字符串。
        /// </summary>
        internal static string medChrgitmType {
            get {
                return ResourceManager.GetString("medChrgitmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用药途径描 述 的本地化字符串。
        /// </summary>
        internal static string medcWayDscr {
            get {
                return ResourceManager.GetString("medcWayDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医疗总费用 的本地化字符串。
        /// </summary>
        internal static string medfeeSumamt {
            get {
                return ResourceManager.GetString("medfeeSumamt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构目录编码 的本地化字符串。
        /// </summary>
        internal static string medinsListCodg {
            get {
                return ResourceManager.GetString("medinsListCodg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医药机构目录名称 的本地化字符串。
        /// </summary>
        internal static string medinsListName {
            get {
                return ResourceManager.GetString("medinsListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医疗机构等级 的本地化字符串。
        /// </summary>
        internal static string medinslv {
            get {
                return ResourceManager.GetString("medinslv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医疗目录编码 的本地化字符串。
        /// </summary>
        internal static string medListCodg {
            get {
                return ResourceManager.GetString("medListCodg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医疗类别 的本地化字符串。
        /// </summary>
        internal static string medType {
            get {
                return ResourceManager.GetString("medType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        internal static string oper_id {
            get {
                return ResourceManager.GetString("oper_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        internal static string oper_time {
            get {
                return ResourceManager.GetString("oper_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手术操作代码 的本地化字符串。
        /// </summary>
        internal static string oprnOprtCode {
            get {
                return ResourceManager.GetString("oprnOprtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手术操作名称 的本地化字符串。
        /// </summary>
        internal static string oprnOprtName {
            get {
                return ResourceManager.GetString("oprnOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人ID 的本地化字符串。
        /// </summary>
        internal static string opterId {
            get {
                return ResourceManager.GetString("opterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人ID 的本地化字符串。
        /// </summary>
        internal static string opterld {
            get {
                return ResourceManager.GetString("opterld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人姓名 的本地化字符串。
        /// </summary>
        internal static string opterName {
            get {
                return ResourceManager.GetString("opterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办机构 的本地化字符串。
        /// </summary>
        internal static string optinsNo {
            get {
                return ResourceManager.GetString("optinsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办时间 的本地化字符串。
        /// </summary>
        internal static string optTime {
            get {
                return ResourceManager.GetString("optTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门诊诊断信息 的本地化字符串。
        /// </summary>
        internal static string otpDiaglnfo {
            get {
                return ResourceManager.GetString("otpDiaglnfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统筹区编码 的本地化字符串。
        /// </summary>
        internal static string poolareaNO {
            get {
                return ResourceManager.GetString("poolareaNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周期天数 的本地化字符串。
        /// </summary>
        internal static string prdDays {
            get {
                return ResourceManager.GetString("prdDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先行自付金额 的本地化字符串。
        /// </summary>
        internal static string preselfpayAmt {
            get {
                return ResourceManager.GetString("preselfpayAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 早产标志 的本地化字符串。
        /// </summary>
        internal static string pretFlag {
            get {
                return ResourceManager.GetString("pretFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 妊娠时间 的本地化字符串。
        /// </summary>
        internal static string preyTime {
            get {
                return ResourceManager.GetString("preyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员证件类型 的本地化字符串。
        /// </summary>
        internal static string psnCertType {
            get {
                return ResourceManager.GetString("psnCertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员姓名 的本地化字符串。
        /// </summary>
        internal static string psnName {
            get {
                return ResourceManager.GetString("psnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 唯一记录号 的本地化字符串。
        /// </summary>
        internal static string rid {
            get {
                return ResourceManager.GetString("rid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单次剂量描述 的本地化字符串。
        /// </summary>
        internal static string sinDosDscr {
            get {
                return ResourceManager.GetString("sinDosDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参保人所属行政区划编码 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中药使用方式 的本地化字符串。
        /// </summary>
        internal static string tcmdrugUsedWay {
            get {
                return ResourceManager.GetString("tcmdrugUsedWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转科室标志 的本地化字符串。
        /// </summary>
        internal static string trafDeptFlag {
            get {
                return ResourceManager.GetString("trafDeptFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        internal static string updtTime {
            get {
                return ResourceManager.GetString("updtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用频次描 述 的本地化字符串。
        /// </summary>
        internal static string usedFrquDscr {
            get {
                return ResourceManager.GetString("usedFrquDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 病区床位 的本地化字符串。
        /// </summary>
        internal static string wardareaBed {
            get {
                return ResourceManager.GetString("wardareaBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住院原因 的本地化字符串。
        /// </summary>
        internal static string ykc679 {
            get {
                return ResourceManager.GetString("ykc679", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补助类型 的本地化字符串。
        /// </summary>
        internal static string ykc680 {
            get {
                return ResourceManager.GetString("ykc680", resourceCulture);
            }
        }
    }
}
